SELECT
  SUBSTRING(A.FECHA,7,4)+SUBSTRING(A.FECHA,4,2)+ SUBSTRING(A.FECHA,1,2) FECHA,
  PRODUCTO,
  UN,
  DESC_PROD,
  CODIGO,
  NOMB_CLTE,
  CANTIDAD,
  M,
  VALOR,
  DSC_EFE,
  NETO,
  IMPORTE,
  VENDEDOR,
  NOMB_VDOR,
  PROMOTOR,
  GIRO,
  DESCRIPCIO,
  ID,
  DOCUMENTO,
  FPAGO,
  MESA,
  TIENDA,
  NOMB_PROV,
  NOMB_DEPT,
  R_U_C_,
  T,
  IDENTICAC,
  ANO,
  MES,
  CLASE,
  DESC_CLAS,
  DIRECCION,
  NOMB_DIST,
  GRUPO,
  NOMB_GRUP,
  LOTE_PRV
FROM MKT.sellout_conti_2015 A


SELECT A.* INTO mkt.SELLOUT_CONTI_HIST
    FROM
(
SELECT * FROM MKT.sellout_conti_2015
UNION ALL
SELECT
  FECHA FECHA,
  ARTICULO PRODUCTO,
  NULL UN,
  DESCRIP DESC_PROD,
  CONVERT(VARCHAR,CONVERT(INT,CLIENTE)) CODIGO,
  NOMBRE NOMB_CLTE,
  CANTIDAD CANTIDAD,
  NULL M,
  NULL VALOR,
  NULL DSC_EFE,
  NETO NETO,
  NULL IMPORTE,
  VENDEDOR VENDEDOR,
  NOMVEN NOMB_VDOR,
  VENDEDORT PROMOTOR,
  SCLIENTE GIRO,
  null DESCRIPCIO,
  ID ID,
  DOCUMTO DOCUMENTO,
  CONVERT(INT,CONDIC) FPAGO,
  MESA MESA,
  --GRUPO,
  CODTDA TIENDA ,
  PROVINCIA NOMB_PROV,
  DEPARTAMEN NOMB_DEPT,
  IDENT R_U_C_,
  NULL T,
  NULL IDENTICAC,
  ANO ANO,
  NULL MES,
  LINEA CLASE,
  NULL DESC_CLAS,
  DIRECC DIRECCION,
  UBICAC NOMB_DIST,
  GRUPO GRUPO,
  NULL NOMB_GRUP,
  NULL LOTE_PRV
FROM MKT.sellout_conti_2014) A

SELECT ID,COUNT(1)  FROM MKT.sellout_conti_2014
GROUP BY ID
ORDER BY 1

SELECT ID, COUNT(1) FROM MKT.sellout_conti_2015
GROUP BY ID
ORDER BY 1

SELECT * FROM MKT.SELLOUT_CONTI_HIST
WHERE LEN(ID)=1

SELECT id, COUNT(1) FROM MKT.SELLOUT_CONTI_HIST
GROUP BY ID
ORDER BY 1

SELECT A.CODIGO,A.R_U_C_,A.NOMB_CLTE,A.DIRECCION,A.NOMB_DIST,A.NOMB_PROV,A.NOMB_DEPT FROM MKT.SELLOUT_CONTI_HIST A

SELECT DISTINCT A.VENDEDOR,A.NOMB_VDOR FROM mkt.SELLOUT_CONTI_HIST A


SELECT DISTINCT Fecha FROM MKT.SELLOUT_CONTI_HIST
WHERE SUBSTRING(FECHA,3,1)<>'/'