

SELECT
  CODIGO,
  DESC_PRODUCTO,
  CANT_COMPRA,
  IMP_COMPRA,
  CANT_VENTA,
  IMP_VENTA,
  STOCK,
  VALOR_STOCK,
  PORCENTAJE,
  PRECIO,
  ARCHIVO
FROM MKT.STOCK_CONTI_2015

SELECT
  B.FECHA,
  A.CODIGO,
  A.DESC_PRODUCTO,
  A.CANT_COMPRA,
  A.IMP_COMPRA,
  A.CANT_VENTA,
  A.IMP_VENTA,
  A.STOCK,
  A.VALOR_STOCK,
  A.PORCENTAJE,
  A.PRECIO
INTO MKT.STOCK_CONTI_HISTW
    FROM MKT.STOCK_CONTI_2015 A
LEFT JOIN
  (SELECT * FROM PER.MAESTRO_TIEMPO WHERE Dia_Semana=7) B
  ON SUBSTRING(A.ARCHIVO,1,4)+SUBSTRING(A.ARCHIVO,6,2)=B.AñoSemana_GL

SELECT * FROM MKT.STOCK_CONTI_2015
ORDER BY 1 ;

stock_cn_daya
SELECT COUNT(1)  FROM MKT.STOCK_CONTI_HISTW;

INSERT INTO MKT.STOCK_CONTI_HISTW
SELECT
  B.FECHA,
  A.CODIGO,
  A.DESC_PRODUCTO,
  A.CANT_COMPRA,
  A.IMP_COMPRA,
  A.CANT_VENTA,
  A.IMP_VENTA,
  A.STOCK,
  A.VALOR_STOCK,
  A.PORCENTAJE,
  A.PRECIO
    FROM MKT.stock_cn_daya A
LEFT JOIN
  (SELECT * FROM PER.MAESTRO_TIEMPO WHERE Dia_Semana=7) B
  ON SUBSTRING(A.ARCHIVO,1,4)+SUBSTRING(A.ARCHIVO,6,2)=B.AñoSemana_GL
