
insert into [mkt].[sellout_inka]
SELECT * FROM [mkt].[sellout_inka_2014]

SELECT * into [mkt].[stock_inkax] FROM [mkt].[stock_inka]

insert into [mkt].[stock_inka]
SELECT * FROM [mkt].[stock_inka_2014]


DROP TABLE [mkt].[sellout_inka_2014]
DROP TABLE [mkt].[stock_inka_2014]





SELECT * FROM [mkt].[sellout_inka]

DROP TABLE mkt.SELLOUT_IK_HISTW
SELECT CONCAT(SUBSTRING([PERIODO],1,4),SUBSTRING(PERIODO,6,2),SUBSTRING(PERIODO,9,2)) Fecha
      ,[COD_PRODUCTO]
      ,[COD_PRODUCTO_PROVEEDOR]
      ,[DESCRIPCION]
      ,[MARCA]
      ,[ESTADO_PROD]
      ,[UMB]
      ,[COD_LOCAL]
      ,[COD_LOCAL_PROVEEDOR]
      ,[DESCRIPCION_LOCAL]
      ,[ESTADO_LOCAL]
      ,[FORMATO]
      ,[TIPO]
      ,[VTA_PERIODO_UNID]
      ,[COSTO_DE_VENTA_PERIODO_S]
	  into mkt.SELLOUT_IK_HISTW
  FROM [genomma].[mkt].[sellout_inka]

/*CHEK FECHA*/

SELECT * FROM mkt.SELLOUT_IK_HISTW A
LEFT JOIN PER.MAESTRO_TIEMPO B
ON A.FECHA=B.FECHA
WHERE B.FECHA IS NULL 




SELECT [COD_PRODUCTO],[DESCRIPCION],COUNT(1) CONTEO,SUM([VTA_PERIODO_UNID]) SUMA FROM mkt.SELLOUT_IK_HISTW a
LEFT JOIN [per].MAESTRO_PRODUCTO_FUENTE B
ON A.[COD_PRODUCTO]=B.PROIDCLIE AND B.GrpID='309'
WHERE B.PROPSTID IS NULL 
GROUP BY [COD_PRODUCTO],[DESCRIPCION]
/*
COD_PRODUCTO	DESCRIPCION	CONTEO	SUMA
108244	TOUCH ME PAÒOLETA COL.SURTIDOS PROMO	43	84.00
*/


DROP TABLE MKT.so_ik_1 ;
SELECT * INTO MKT.so_ik_1 FROM mkt.SELLOUT_IK_HISTW
WHERE COD_PRODUCTO<>'108244'


DROP TABLE MKT.so_ik_2;
SELECT 
A.Fecha,
A.COD_PRODUCTO,
A.COD_LOCAL,
SUM(A.VTA_PERIODO_UNID) VTA_PERIODO_UNID,
SUM(A.COSTO_DE_VENTA_PERIODO_S) COSTO_DE_VENTA_PERIODO_S
INTO MKT.so_ik_2
FROM MKT.so_ik_1 A
GROUP BY Fecha,COD_PRODUCTO,COD_LOCAL


/* check producto*/

insert into per.MAESTRO_PRODUCTO_FUENTE
SELECT 
COD_PRODUCTO,
'309' GRPID,
'0000' PROPSTID
FROM
(
SELECT DISTINCT COD_PRODUCTO FROM MKT.so_ik_2 a
LEFT JOIN [per].MAESTRO_PRODUCTO_FUENTE B
ON A.COD_PRODUCTO=B.PROIDCLIE AND B.GrpID='309'
WHERE B.PROPSTID IS NULL 
) A;

/* check TIEMPO*/

/* check pdv*/
insert into [per].maestro_pdv
SELECT 
NEXT VALUE FOR per.seq_PDVid OVER(ORDER BY [COD_LOCAL]),
	[COD_LOCAL],
	[COD_LOCAL],
	[COD_LOCAL],
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	'309'
FROM 
(
SELECT DISTINCT [COD_LOCAL]  FROM MKT.so_ik_2 A
LEFT JOIN [per].maestro_pdv PD
ON [COD_LOCAL]=PD.PdvIDClie  AND PD.GrpID='309'
WHERE PDVID IS NULL 
) A;

SELECT * FROM per.MAESTRO_PDV
/*CHECK PRECIO*/

insert into [per].MAESTRO_PRODUCTO_PRECIO
SELECT 
NEXT VALUE FOR [per].[seq_precioid] OVER(ORDER BY [GrpID],[ProPstID],AÒoSemana_GL),
A.*
FROM 
(
SELECT 
'309' GRPID,PROPSTID,AÒoSemana_GL,0 PRECIO FROM
(
SELECT Q.PROPSTID,Q.AÒoSemana_GL FROM
(
SELECT DISTINCT B.PROPSTID,T.AÒoSemana_GL FROM
mkt.so_ik_2 A
LEFT JOIN per.MAESTRO_PRODUCTO_FUENTE B
ON A.COD_PRODUCTO=B.PROIDCLIE
LEFT JOIN per.MAESTRO_TIEMPO T
ON A.FECHA=T.Fecha
) Q LEFT JOIN per.MAESTRO_PRODUCTO_PRECIO H
ON H.GrpID='309' AND H.AÒOSEMANA_GL=Q.AÒoSemana_GL AND H.ProPstID=Q.PROPSTID
WHERE H.PrecioLista IS NULL 
) P
) A;


DROP TABLE per.SELLOUT_IK;
SELECT 
A.Fecha,
NULL [CadenaID],
NULL [OficinaID],
NULL [GrupoTratID],
NULL [VendedorID],
G.ProPstID,
PD.PdvID,
H.PrecioID,
A.VTA_PERIODO_UNID UnidDesp,
A.COSTO_DE_VENTA_PERIODO_S MontoDespCliente,
A.VTA_PERIODO_UNID*H.PRECIOLISTA MontoDesp,
T.AÒoSemana_GL
into per.SELLOUT_IK
FROM [mkt].so_ik_2 A
LEFT JOIN per.maestro_producto_fuente G
ON G.[GrpID]='309' AND A.COD_PRODUCTO=G.PROIDCLIE
LEFT JOIN per.maestro_pdv PD
ON A.COD_LOCAL=PD.PdvIDClie AND PD.GrpID='309'
LEFT JOIN per.[maestro_tiempo] T
ON A.Fecha=T.Fecha
LEFT JOIN per.[maestro_producto_precio] H
ON H.GrpID='309' AND H.AÒOSEMANA_GL=T.AÒoSemana_GL AND H.ProPstID=G.PROPSTID


SELECT * FROM per.SELLOUT_IK


ALTER TABLE [per].[SELLOUT_IK] with check
ADD CONSTRAINT FK_SOIK_PRO FOREIGN KEY (PROPSTID)
REFERENCES per.[MAESTRO_PRODUCTO_PRESENTACION](PROPSTID)

ALTER TABLE per.MAESTRO_TIEMPO ALTER COLUMN FECHA VARCHAR(8) NOT NULL;
alter table per.MAESTRO_TIEMPO add primary key (FECHA);

ALTER TABLE [per].[SELLOUT_IK] with check
ADD CONSTRAINT FK_SOIK_TIM FOREIGN KEY (FECHA)
REFERENCES per.[MAESTRO_TIEMPO](FECHA)


ALTER TABLE [per].[SELLOUT_IK] ALTER COLUMN [CadenaID] VARCHAR(4) NULL;
ALTER TABLE [per].[SELLOUT_IK] ALTER COLUMN [OficinaID] VARCHAR(4) NULL;
ALTER TABLE [per].[SELLOUT_IK] ALTER COLUMN [GrupoTratID] VARCHAR(4) NULL;
ALTER TABLE [per].[SELLOUT_IK] ALTER COLUMN [VendedorID] VARCHAR(6) NULL;



ALTER TABLE [per].[SELLOUT_IK] with check
ADD CONSTRAINT FK_SOIK_VEN FOREIGN KEY ([VendedorID])
REFERENCES per.[MAESTRO_VENDEDOR]([VendedorID])

ALTER TABLE [per].[SELLOUT_IK] with check
ADD CONSTRAINT FK_SOIK_cad FOREIGN KEY ([CadenaID])
REFERENCES per.[MAESTRO_CADENA]([CadenaID])

ALTER TABLE [per].[SELLOUT_IK] with check
ADD CONSTRAINT FK_SOIK_OFI FOREIGN KEY ([OficinaID])
REFERENCES per.[MAESTRO_OFICINA]([OficinaID])

ALTER TABLE [per].[SELLOUT_IK] with check
ADD CONSTRAINT FK_SOIK_G1 FOREIGN KEY ([GrupoTratID])
REFERENCES per.[MAESTRO_GRUPO1](Grupo1id)

ALTER TABLE [per].[SELLOUT_IK] with check
ADD CONSTRAINT FK_SOIK_pdv FOREIGN KEY ([PdvID])
REFERENCES per.[MAESTRO_PDV]([PdvID])

ALTER TABLE [per].[SELLOUT_IK] with check
ADD CONSTRAINT FK_SOIK_PRE FOREIGN KEY ([PrecioID])
REFERENCES per.[MAESTRO_PRODUCTO_PRECIO]([PrecioID])

ALTER TABLE [per].[SELLOUT_IK] with check
ADD CONSTRAINT FK_SOIK_GRP FOREIGN KEY ([GrpID])
REFERENCES per.[MAESTRO_CLIENTE]([GrpID])

ALTER TABLE [per].[SELLOUT_IK] ALTER COLUMN [SupervisorID] VARCHAR(6) NULL;
ALTER TABLE [per].[SELLOUT_IK] with check
ADD CONSTRAINT FK_SOIK_SUP FOREIGN KEY ([SupervisorID])
REFERENCES per.[MAESTRO_SUPERVISOR]([SupervisorID])






