SELECT * FROM per.MAESTRO_PDV
WHERE PdvIDClie=PdvNombre
and GrpID='307'

SELECT * FROM per.MAESTRO_PRODUCTO_FUENTE
WHERE ProPstID='0000'
and GrpID='307'

SELECT * FROM per.MAESTRO_VENDEDOR
WHERE VendedorIDClie=DescVendedor
and GrpID='307'

SELECT * FROM per.MAESTRO_SUPERVISOR
WHERE SupervisorIDClie=DescSupervisor
and GrpID='307'

SELECT
DISTINCT
A.PdvID,
B.CODIGO,
B.R_U_C_,
B.NOMB_CLTE,
B.DIRECCION,
B.NOMB_DEPT,
B.NOMB_PROV,
B.NOMB_DIST
FROM
(
SELECT *
FROM per.MAESTRO_PDV
WHERE PdvIDClie = PdvNombre
      AND GrpID = '327'
) A LEFT JOIN mkt.SELLOUT_CONTI_HISTW B
  ON A.PdvIDClie=CONVERT(VARCHAR,CONVERT(BIGINT,B.CODIGO))

SELECT a.GrpID,a.ProIDClie,COALESCE(B.DESC_PROD,C.DESC_PRODUCTO) ProPstNombreClie FROM
(
SELECT * FROM per.MAESTRO_PRODUCTO_FUENTE
WHERE ProPstID='0000'
AND GrpID='327'
) A LEFT JOIN mkt.SELLOUT_CONTI_HISTW B
  ON A.ProIDClie=CONVERT(VARCHAR,CONVERT(BIGINT,B.PRODUCTO))
LEFT JOIN mkt.STOCK_CONTI_HISTW C
  ON A.ProIDClie=CONVERT(VARCHAR,CONVERT(BIGINT,C.CODIGO))



SELECT * FROM per.MAESTRO_VENDEDOR
WHERE VendedorIDClie=DescVendedor
and GrpID='327'

SELECT * FROM per.MAESTRO_SUPERVISOR
WHERE SupervisorIDClie=DescSupervisor
and GrpID='327'

/******************************************/
/*DIGALIMENTA*/
/*********************************************/
SELECT
DISTINCT
A.PdvID,
A.PdvIDClie,
B.COD_CLIENTE,
B.DOC_IDENTIDAD,
B.NOM_CLIENTE,
B.DIRECCION,
B.DEPARTAMENTO,
B.PROVINCIA,
B.DISTRITO
FROM
(
SELECT *
FROM per.MAESTRO_PDV
WHERE PdvIDClie <> PdvNombre
      AND GrpID = '337'
) A LEFT JOIN mkt.SELLOUT_DIGA_HISTW B
  ON A.PdvIDClie=CONVERT(VARCHAR,CONVERT(BIGINT,B.COD_CLIENTE))

SELECT * FROM per.MAESTRO_PDV
WHERE PdvIDClie IN (
'80495',
'91054',
'92549',
'91770',
'96141',
'13489',
'17900',
'72601',
'59386',
'69916',
'69529')



SELECT LEN(COD_CLIENTE),MAX(COD_CLIENTE),MAX(NOM_CLIENTE) FROM mkt.SELLOUT_DIGA_HISTW
GROUP BY LEN(COD_CLIENTE)

SELECT DISTINCT COD_CLIENTE,NOM_CLIENTE,DOC_IDENTIDAD FROM mkt.SELLOUT_DIGA_HISTW
WHERE COD_CLIENTE LIKE '%8049%'


SELECT * FROM per.MAESTRO_PDV
WHERE PdvIDClie=PdvNombre
and GrpID='337'

SELECT * FROM per.MAESTRO_PRODUCTO_FUENTE
WHERE ProPstID='0000'
and GrpID='337'

SELECT * FROM per.MAESTRO_VENDEDOR
WHERE VendedorIDClie=DescVendedor
and GrpID='337'

SELECT * FROM per.MAESTRO_SUPERVISOR
WHERE SupervisorIDClie=DescSupervisor
and GrpID='337'

SELECT * FROM per.MAESTRO_PDV
WHERE PdvIDClie=PdvNombre
and GrpID='338'

SELECT * FROM per.MAESTRO_PRODUCTO_FUENTE
WHERE ProPstID='0000'
and GrpID='338'

SELECT * FROM per.MAESTRO_VENDEDOR
WHERE VendedorIDClie=DescVendedor
and GrpID='338'

SELECT * FROM per.MAESTRO_SUPERVISOR
WHERE SupervisorIDClie=DescSupervisor
and GrpID='338'

SELECT * FROM per.MAESTRO_PDV
WHERE PdvIDClie=PdvNombre
and GrpID='309'

SELECT * FROM per.MAESTRO_PRODUCTO_FUENTE
WHERE ProPstID='0000'
and GrpID='309'

SELECT * FROM per.MAESTRO_VENDEDOR
WHERE VendedorIDClie=DescVendedor
and GrpID='309'

SELECT * FROM per.MAESTRO_SUPERVISOR
WHERE SupervisorIDClie=DescSupervisor
and GrpID='309'