SELECT
  SUBSTRING(RTRIM(LTRIM(FECHA)),1,8) FECHA,
  CONVERT(VARCHAR,CONVERT(DECIMAL(18,0),REPLACE(RTRIM(LTRIM(COD_PDV)),',','.'))) COD_PDV,
  DESC_PDV,
  CONVERT(VARCHAR,CONVERT(DECIMAL(18,0),REPLACE(RTRIM(LTRIM(COD_PROD)),',','.'))) COD_PROD,
  CAST ( RTRIM(LTRIM(COD_PRODP)) AS VARCHAR(20)) COD_PRODP,
  DESC_PROD,
  CONVERT(DECIMAL(15,6),REPLACE(RTRIM(LTRIM(CANTIDAD)),',','.')) CANTIDAD,
  CONVERT(DECIMAL(15,6),REPLACE(RTRIM(LTRIM(NETO)),',','.')) NETO,
  ARCHIVO
INTO mkt.SELLOUT_TOTTUS_HISTW
FROM mkt.SELLOUT_TOTTUS_HIST;



SELECT COD_PROD,DESC_PROD,SUM(CANTIDAD),SUM(NETO) FROM mkt.SELLOUT_TOTTUS_HISTW
  GROUP BY COD_PROD,DESC_PROD


SELECT DISTINCT LEN(COD_PROD),COD_PROD FROM mkt.SELLOUT_TOTTUS_HISTW
ORDER BY 1 DESC