DROP TABLE  mkt.STOCK_DIGA_HIST

SELECT * FROM  MKT.SELLOUT_DIGA_HIST
WHERE SUBSTRING(FECHA,3,1)='/'


SELECT * FROM MKT.STOCK_DIGA_HIST
WHERE SUBSTRING(FECHA,3,1)='/'


SELECT * FROM MKT.SELLOUT_KEYMARK_HIST

SELECT * FROM MKT.STOCK_KEYMARK_HIST



EXEC sp_help 'MKT.SELLOUT_DIGA_HIST'


SELECT DISTINCT TIPO_CLIENTE FROM MKT.SELLOUT_DIGA_HIST

SELECT * FROM  MKT.SELLOUT_DIGA_HIST