select * from [mkt].[stock_qui_suiza]




SELECT  
[GRUPO_ARTICULO]
,[Codigo_SAP]
      ,[COD_PROV]
      ,[NOMPROD]
      ,[CD_CENTRO]
      ,[CD_ALMACEN]
      ,[Stock_Especial]
      ,[Num_Stock_Especial]
      ,[LOTE]
	  ,[CANT_01]
      ,CASE WHEN len([CANT_01])=12 THEN CAST(SUBSTRING([CANT_01],2,11) AS DECIMAL(12,3))/-1000 ELSE CAST([CANT_01] AS DECIMAL(12,3))/1000 END [CANT_01]
      ,CASE WHEN len([CANT_02])=12 THEN CAST(SUBSTRING([CANT_02],2,11) AS DECIMAL(12,3))/-1000 ELSE CAST([CANT_02] AS DECIMAL(12,3))/1000 END [CANT_02]
      ,CASE WHEN len([CANT_03])=12 THEN CAST(SUBSTRING([CANT_03],2,11) AS DECIMAL(12,3))/-1000 ELSE CAST([CANT_03] AS DECIMAL(12,3))/1000 END [CANT_03]
      ,CASE WHEN len([CANT_04])=12 THEN CAST(SUBSTRING([CANT_04],2,11) AS DECIMAL(12,3))/-1000 ELSE CAST([CANT_04] AS DECIMAL(12,3))/1000 END [CANT_04]
      ,[UNIDAD_MEDIDA]
      ,[FEC_VCMTO_LOTE]
      ,[FEC_PROCESO]
FROM [genomma].[mkt].[stock_qui_suiza]

SELECT * FROM [genomma].[mkt].[sellout_qui_suiza]

SELECT [ID]
      ,[FECHAGEN]
      ,[VBRP_MATKL]
      ,[VBRP_MATNR]
      ,[WPROD]
      ,[VBRK_KUNAG]
      ,[KNA1_STCD1]
      ,[UBIGEO]
      ,[COD_VEND]
      ,[COD_PROM]
      ,[FREE1]
      ,[COD_OFI]
      ,[COD_CENTRO]
      ,[COD_ALM]
      ,[VBAK_VBELN]
      ,[VBKD_BSARK_E]
      ,[VBRK_VBELN]
      ,[VBRP_POSNR]
      ,[VBRK_XBLNR]
      ,[VBRK_ERDAT]
      ,[VBRK_FKART]
      ,[VBRK_FKDAT]
      ,[VBRK_ZZRFOFI]
      ,[VBRP_CHARG]
      ,[VBRK_ZTERM]
      ,[VBRP_AUGRU_AUFT]
      ,[VBRK_FKSTO]
      ,[VBRP_FKIMG]
	  ,CASE WHEN len([VBRP_FKIMG])=12 THEN CAST(SUBSTRING([VBRP_FKIMG],2,11) AS DECIMAL(12,3))/-1000 ELSE CAST([VBRP_FKIMG] AS DECIMAL(12,3))/1000 END [VBRP_FKIMG]
      ,[VBRP_VRKME]
	  ,CAST([VBRP_ZZ_ZP01] AS DECIMAL(12,2))/100 [VBRP_ZZ_ZP01]
      ,[VBRK_WAERK]
      ,CAST([DESC_RR] AS DECIMAL(6,2))/100 [DESC_RR]
	  ,CAST([DESC_NR] AS DECIMAL(6,2))/100 [DESC_NR]
      ,CASE WHEN len([VBRP_KZWI1])=12 THEN CAST(SUBSTRING([VBRP_KZWI1],2,11) AS DECIMAL(12,2))/-1000 ELSE CAST([VBRP_KZWI1] AS DECIMAL(12,2))/1000 END [VBRP_KZWI1]
	  ,CASE WHEN len([ZVALVTA_UNI])=12 THEN CAST(SUBSTRING([ZVALVTA_UNI],2,11) AS DECIMAL(12,2))/-1000 ELSE CAST([ZVALVTA_UNI] AS DECIMAL(12,2))/1000 END [ZVALVTA_UNI]
	  ,CASE WHEN len([ZIMP_BRUTO])=12 THEN CAST(SUBSTRING([ZIMP_BRUTO],2,11) AS DECIMAL(12,2))/-1000 ELSE CAST([ZIMP_BRUTO] AS DECIMAL(12,2))/1000 END [ZIMP_BRUTO]
      ,CAST([ZMARGEN] AS DECIMAL(6,2))/100 [ZMARGEN]
	  ,CASE WHEN len([ZVAL_VTAIMP])=12 THEN CAST(SUBSTRING([ZVAL_VTAIMP],2,11) AS DECIMAL(12,2))/-1000 ELSE CAST([ZVAL_VTAIMP] AS DECIMAL(12,2))/1000 END [ZVAL_VTAIMP]
      ,CASE WHEN len([ZIMP_IMPTO])=12 THEN CAST(SUBSTRING([ZIMP_IMPTO],2,11) AS DECIMAL(12,2))/-1000 ELSE CAST([ZIMP_IMPTO] AS DECIMAL(12,2))/1000 END [ZIMP_IMPTO]
      ,CAST([DESC_QS] AS DECIMAL(6,2))/100 [DESC_QS]
      ,CASE WHEN len([ZVALNETO])=12 THEN CAST(SUBSTRING([ZVALNETO],2,11) AS DECIMAL(12,2))/-1000 ELSE CAST([ZVALNETO] AS DECIMAL(12,2))/1000 END [ZVALNETO]
      ,[CLS_PED]
      ,[IND_BONIF]
	  ,CASE WHEN len([ZVALNET_CFLETE])=12 THEN CAST(SUBSTRING([ZVALNET_CFLETE],2,11) AS DECIMAL(12,2))/-1000 ELSE CAST([ZVALNET_CFLETE] AS DECIMAL(12,2))/1000 END [ZVALNET_CFLETE]
	  ,CASE WHEN len([VAL_DESC_RR])=12 THEN CAST(SUBSTRING([VAL_DESC_RR],2,11) AS DECIMAL(12,2))/-1000 ELSE CAST([VAL_DESC_RR] AS DECIMAL(12,2))/1000 END [VAL_DESC_RR]
      ,CASE WHEN len([VAL_DESC_NR])=12 THEN CAST(SUBSTRING([VAL_DESC_NR],2,11) AS DECIMAL(12,2))/-1000 ELSE CAST([VAL_DESC_NR] AS DECIMAL(12,2))/1000 END [VAL_DESC_NR]
	  ,CASE WHEN len([VAL_DESC_QS])=12 THEN CAST(SUBSTRING([VAL_DESC_QS],2,11) AS DECIMAL(12,2))/-1000 ELSE CAST([VAL_DESC_QS] AS DECIMAL(12,2))/1000 END [VAL_DESC_QS]
	  ,CASE WHEN len([VAL_FLETE_APROV])=12 THEN CAST(SUBSTRING([VAL_FLETE_APROV],2,11) AS DECIMAL(12,2))/-1000 ELSE CAST([VAL_FLETE_APROV] AS DECIMAL(12,2))/1000 END [VAL_FLETE_APROV]
      ,CASE WHEN len([ZVALNETO_SF_QS])=12 THEN CAST(SUBSTRING([ZVALNETO_SF_QS],2,11) AS DECIMAL(12,2))/-1000 ELSE CAST([ZVALNETO_SF_QS] AS DECIMAL(12,2))/1000 END [ZVALNETO_SF_QS]
      ,CAST([TIPO_CAMBIO] AS DECIMAL(12,5))/100000 [DESC_NR]
      ,CAST([PJE_DSCTO_CE] AS DECIMAL(5,2))/100 [PJE_DSCTO_CE]
	  ,CASE WHEN len([VALOR_DSCTO_CE])=12 THEN CAST(SUBSTRING([VALOR_DSCTO_CE],2,11) AS DECIMAL(12,2))/-1000 ELSE CAST([VALOR_DSCTO_CE] AS DECIMAL(12,2))/1000 END [VALOR_DSCTO_CE]
      ,CASE WHEN len([COSTO_UNIT])=12 THEN CAST(SUBSTRING([COSTO_UNIT],2,11) AS DECIMAL(12,2))/-1000 ELSE CAST([COSTO_UNIT] AS DECIMAL(12,2))/1000 END [COSTO_UNIT]
      ,[ORG_VTAS]
      ,[SECTOR]
      ,[CARACT_NEG]
      ,[TRAT_COMERCIAL]
  FROM [genomma].[mkt].[sellout_qui_suiza]




  SELECT len([COSTO_UNIT]),COUNT(1)  FROM [genomma].[mkt].[sellout_qui_suiza]
  GROUP BY len([COSTO_UNIT]);

  SELECT len([ZIMP_IMPTO]),[ZIMP_IMPTO]  FROM [genomma].[mkt].[sellout_qui_suiza]
  ORDER BY  len([ZIMP_IMPTO]) desc;

  SELECT DISTINCT substring([ZIMP_IMPTO],1,1) FROM [genomma].[mkt].[sellout_qui_suiza];


SELECT * FROM  mkt.sellout_digalimenta

SELECT COUNT(1)  FROM  mkt.stock_digalimenta


SELECT substring(fecha,1,10)FROM MKT.sellout_continental

SELECT DISTINCT LEN(valor) FROM MKT.sellout_conti
ORDER BY 1 desc

SELECT [VENDEDOR], LEN([VENDEDOR]) FROM mkt.sellout_continental
ORDER BY 2 desc


SELECT valor, LEN(valor) FROM mkt.sellout_conti
ORDER BY 2 desc



SELECT cantidad FROM mkt.sellout_conti
ORDER BY cantidad asc


-6,0

DROP TABLE  mkt.sellout_conti

SELECT valor, len(valor),str(valor) FROM mkt.sellout_conti
ORDER BY 1 desc



SELECT max(NETO),min(NETO) FROM mkt.sellout_conti 


SELECT * FROM  mkt.sellout_conti 
ORDER BY cantidad asc





SELECT [CODIGO]
      ,[DESC_PRODUCTO]
      ,[CANT_COMPRA]
      ,[IMP_COMPRA]/100 [IMP_COMPRA]
      ,[CANT_VENTA]
      ,[IMP_VENTA]/100 [IMP_VENTA]
      ,[STOCK]
      ,[VALOR_STOCK]/100 [VALOR_STOCK]
      ,cast (replace([PORCENTAJE],'%','') as decimal(5,2))/100 [PORCENTAJE]
      ,[PRECIO]/100 [PRECIO]
into mkt.st_conti
FROM [genomma].[mkt].[stock_conti]


SELECT * FROM mkt.st_conti



SELECT DISTINCT A.COD_PROD, A.DESCR_PROD FROM [mkt].[sellout_digalimenta] A

SELECT * FROM [mkt].[sellout_qui_suiza]

SELECT DISTINCT FECHA FROM [mkt].[sellout_digalimenta]
ORDER BY 1

SELECT FECHAgen, COUNT(1) FROM   [mkt].[sellout_qui_suiza]
GROUP BY FECHAgen


SELECT VBRK_FKDAT ,COUNT(1) FROM [mkt].[sellout_qui_suiza]
GROUP BY VBRK_FKDAT
ORDER BY 1



SELECT  substring(VBRK_FKDAT,1,6) ,COUNT(1)  FROM MKT.SELLOUT_QS_HIST
GROUP BY substring(VBRK_FKDAT,1,6)
ORDER BY  1

SELECT DISTINCT WPROD
 FROM  MKT.SELLOUT_QS_HIST



SELECT * FROM [mkt].[sellout_digalimenta]


SELECT FECHAGEN,COUNT(1) FROM MKT.SELLOUT_QS_HIST
WHERE WPROD IS NULL 
GROUP BY FECHAGEN
ORDER BY 1

/*******************************
DIGALIMENTA
***************************************/

SELECT 
MIN(CONVERT( VARCHAR,convert(datetime, [FECHA], 103),112)) MIN_FECHA,
MAX(CONVERT( VARCHAR,convert(datetime, [FECHA], 103),112)) MAX_FECHA
FROM [genomma].[mkt].[sellout_digalimenta]
/*
MIN_FECHA	MAX_FECHA
20141025	20150420
*/

SELECT CONVERT( VARCHAR,convert(datetime, [FECHA], 103),112) [FECHA]
      ,[COD_SUCURSAL]
      ,[NOM_SUCURSAL]
      ,[TIPO_CLIENTE]
      ,[COD_CLIENTE]
      ,[DOC_IDENTIDAD]
      ,[NOM_CLIENTE]
      ,[DIRECCION]
      ,[DISTRITO]
      ,[PROVINCIA]
      ,[DEPARTAMENTO]
      ,[COD_SUPER]
      ,[NOM_SUPER]
      ,[COD_VEND]
      ,[NOM_VEND]
      ,[COD_PROD]
      ,[DESCR_PROD]
      ,[CANTIDAD]
      ,[VALORVTA]
FROM [genomma].[mkt].[sellout_digalimenta]
ORDER BY 1 ASC



SELECT CONVERT( VARCHAR,convert(datetime, [FECHA], 103),112),COUNT(1)   FROM [genomma].[mkt].[sellout_digalimenta]
GROUP BY CONVERT( VARCHAR,convert(datetime, [FECHA], 103),112)
ORDER BY 1 ASC


SELECT * FROM [mkt].[stock_digalimenta]




