SELECT * FROM [mkt].[SELLOUT_QS_HISTW]


SELECT COUNT(DISTINCT  A.VBRK_KUNAG) FROM [mkt].[SELLOUT_QS_HISTW] A



SELECT VBRK_FKDAT,COUNT(1)  FROM [mkt].[SELLOUT_QS_HISTW]
GROUP BY VBRK_FKDAT
ORDER BY 1 DESC




SELECT * FROM [mkt].[SELLOUT_QS_HISTW]
WHERE VBRK_FKDAT='20150331'
and ZVALNETO_SF_QS<0


SELECT VBRP_MATNR,COUNT(DISTINCT VBRK_KUNAG),
COUNT(DISTINCT (CASE WHEN ZVALNETO_SF_QS>0 THEN VBRK_KUNAG end)) cobertura,
COUNT(DISTINCT (CASE WHEN ZVALNETO_SF_QS<=0 THEN VBRK_KUNAG end)) nocobertura
FROM [mkt].[SELLOUT_QS_HISTW]
WHERE VBRK_FKDAT='20150331'
GROUP BY VBRP_MATNR
ORDER BY 1

166333	16	15	2

SELECT VBRK_KUNAG,ZVALNETO_SF_QS 
FROM [mkt].[SELLOUT_QS_HISTW]
WHERE VBRK_FKDAT='20150331'
and  VBRP_MATNR='502263'
ORDER BY 1





SELECT VBRK_FKDAT,VBRP_MATNR,ZVALNETO_SF_QS,VBRP_FKIMG FROM [mkt].[SELLOUT_QS_HISTW]
WHERE VBRK_KUNAG='0000342327'
ORDER BY VBRK_FKDAT DESC





SELECT 
VBRK_FKDAT,VBRK_KUNAG,VBRP_MATNR,sum(a.VBRP_FKIMG) CANT, SUM(ZVALNETO_SF_QS) IMPORTE
into [mkt].[SELLOUT_QS_AGRUP]
FROM [mkt].[SELLOUT_QS_HISTW] a
GROUP BY 
VBRK_FKDAT,VBRK_KUNAG,VBRP_MATNR
ORDER BY 1 desc ,2 desc









SELECT VBRK_FKDAT,COUNT(1)  FROM [mkt].[SELLOUT_QS_HISTW]
WHERE VBRK_KUNAG='0000342327'
GROUP BY VBRK_FKDAT
ORDER BY VBRK_FKDAT DESC



SELECT * FROM [mkt].[SELLOUT_QS_HISTW]
WHERE VBRK_ERDAT<>VBRK_FKDAT




/* casos facturacion*/

SELECT 
CASE WHEN ZVALNETO_SF_QS<0 THEN 'DEVOLUCION'
WHEN ZVALNETO_SF_QS=0 THEN 'CEROS' 
WHEN ZVALNETO_SF_QS>0 THEN 'VENTA' end TIPO_VENTA,
VBRK_FKART,COUNT(1) 
FROM [mkt].[SELLOUT_QS_HISTW]
GROUP BY 
CASE WHEN ZVALNETO_SF_QS<0 THEN 'DEVOLUCION'
WHEN ZVALNETO_SF_QS=0 THEN 'CEROS' 
WHEN ZVALNETO_SF_QS>0 THEN 'VENTA' end,
VBRK_FKART
ORDER BY 2,1






SELECT * FROM  [mkt].[sellout_digalimenta]
ORDER BY fecha asc







