SELECT DISTINCT VBRK_KUNAG
 FROM [mkt].[SELLOUT_QS_HISTW]

 SELECT DISTINCT COD_CENTRO FROM [mkt].[SELLOUT_QS_HISTW]



 /*
 ENTIDAD PUNTO DE VENTA
 */

 SELECT DISTINCT 
 NULL PDVID,
 VBRK_KUNAG COD_CLI_PDV,
 KNA1_STCD1 RUC,NULL PDVNOMBRE,
 NULL STATUS, 
 NULL DIRECCION,
 NULL GEO_DISTRITO,
 NULL GEO_PROVINCIA,
 NULL GEO_DEPARTAMENTO
 INTO MKT.ENT_PDV
 FROM  [mkt].[SELLOUT_QS_HISTW]

 /*
 ENTIDAD PRODUCTO
 */
 
SELECT DISTINCT 
NULL PROPSTID,
VBRP_MATNR ProIDClie,
NULL EAN,
NULL PROPSTCODBARRAS,
NULL PROPSTCODIGOATLAS,
NULL PROPSTNOMBRE,
NULL PROID,
NULL PRONOMBRE,
NULL AGRPROID,
NULL AGRPRONOMBRE,
NULL LINID,
NULL LINNOMBRE,
NULL MRCID,
NULL MRCNOMBRE,
NULL STATUS
FROM  [mkt].[SELLOUT_QS_HISTW]

/*ENTIDAD LINEA PRODUCTO*/
SELECT 
NULL LINID,
NULL LINNOMBRE

/*
ENTIDAD MARCA PRODUCTO*/
SELECT 
NULL MRCID,
NULL MRCNOMBRE

/*ENTIDAD PRECIO*/

SELECT DISTINCT 
NULL PRECIOID,
NULL GRPID,
NULL PROPSTID,
NULL PRECIO_LISTA,
NULL AÑOSEMANA_GL
FROM  [mkt].[SELLOUT_QS_HISTW]

/*ENTIDAD CLIENTE*/

SELECT DISTINCT 
NULL GRPID,
NULL GRUPO,
NULL CANAL
FROM [mkt].[SELLOUT_QS_HISTW]
