/*CHEKANDO SI PRECIO NULOS SON USADOS POR LA FACT TABLE
SI LO SON: DE TODAS MANERAS SE ELIMINO LOS REGISTROS
*/
SELECT B.ProPstID,C.PROPSTID,D.ProPstNombre,MIN(T.AÒOSEMANA_GL),MAX(T.AÒOSEMANA_GL) FROM MKT.SO_QS_SUM A
LEFT JOIN 
mkt.maestro_fuente_producto C
ON A.VBRP_MATNR=C.PROIDCLIE
LEFT JOIN 
MKT.maestro_tiempo T
ON A.VBRK_FKDAT=T.Fecha
INNER JOIN 
(
SELECT * FROM MKT.MAESTRO_PRECIO P
WHERE PRECIO_LISTA IS NULL AND GrpID='307' 
) B
ON C.ProPstID=B.ProPstID AND T.AÒOSEMANA_GL=B.AÒOSEMANA_GL AND B.GrpID='307'
LEFT JOIN
MKT.maestro_presentacion_producto D
ON D.ProPstID=B.ProPstID
GROUP BY B.ProPstID,C.PROPSTID,D.ProPstNombre
ORDER BY 1


SELECT A.ProPstID,B.PROPSTID,B.ProPstNombre,COUNT(1) VECES,MIN(A.AÒOSEMANA_GL) MINIMO_AS,MAX(AÒOSEMANA_GL) MAXIMO_AS FROM
(
SELECT * FROM MKT.MAESTRO_PRECIO
WHERE PRECIO_LISTA IS NULL AND GrpID='307'
) A
LEFT JOIN
MKT.maestro_presentacion_producto B
ON A.ProPstID=B.ProPstID
GROUP BY A.ProPstID,B.PROPSTID,B.ProPstNombre


SELECT * FROM MKT.MAESTRO_PRECIO
WHERE PRECIO_LISTA IS NULL 
AND PROPSTID IS NULL 