 SELECT 
SUBSTRING([FECHA],7,4)+SUBSTRING(FECHA,4,2)+SUBSTRING(FECHA,1,2) FECHA
      ,[COD_SUCURSAL]
      ,[NOM_SUCURSAL]
      ,[TIPO_CLIENTE]
      ,[COD_CLIENTE]
      ,[DOC_IDENTIDAD]
      ,[NOM_CLIENTE]
      ,[DIRECCION]
      ,[DISTRITO]
      ,[PROVINCIA]
      ,[DEPARTAMENTO]
      ,[COD_SUPER]
      ,[NOM_SUPER]
      ,[COD_VEND]
      ,[NOM_VEND]
      ,[COD_PROD]
      ,[DESCR_PROD]
      ,[CANTIDAD]
      ,[VALORVTA]
	  INTO [mkt].[sellout_digalimentaX]
FROM [mkt].[sellout_digalimenta]


DROP TABLE [mkt].[sellout_digalimenta]
EXEC sp_rename 'mkt.sellout_digalimentax', 'sellout_digalimenta';
 
 
 
DROP TABLE mkt.DG_recompra_01;
 
DECLARE @mydate DATE
DECLARE @mydateini DATE
SELECT @mydate = '20150420';
SELECT @mydateini=dateadd(dd,-day(@mydate)+1,convert(date,@mydate,112));
PRINT(@mydateini);
SELECT 
SUBSTRING(FECHA,1,6) PERIODO,COD_CLIENTE,COD_PROD,sum(CANTIDAD) cantidad
into mkt.DG_recompra_01
FROM [mkt].[sellout_digalimenta]
WHERE dateadd(dd,-day(FECHA)+1,convert(date,FECHA,112))<= @mydateini AND 
		dateadd(dd,-day(FECHA)+1,convert(date,FECHA,112))>= dateadd(mm,-6,@mydateini)
		GROUP BY SUBSTRING(FECHA,1,6),COD_CLIENTE,COD_PROD
		ORDER BY 1;


DROP TABLE mkt.DG_recompra_02;
SELECT 
A.PERIODO,A.COD_CLIENTE,A.COD_PROD,
SUM(CASE WHEN B.PERIODO = '201503' THEN 1 ELSE 0 END) COMPRAM1,
SUM(CASE WHEN B.PERIODO = '201503' THEN A.CANTIDAD ELSE 0 END) CANT_COMPRAM1,
SUM(CASE WHEN B.PERIODO = '201502' THEN 1 ELSE 0 END) COMPRAM2,
SUM(CASE WHEN B.PERIODO = '201502' THEN A.CANTIDAD ELSE 0 END) CANT_COMPRAM2,
SUM(CASE WHEN B.PERIODO = '201501' THEN 1 ELSE 0 END) COMPRAM3,
SUM(CASE WHEN B.PERIODO = '201501' THEN A.CANTIDAD ELSE 0 END) CANT_COMPRAM3,
SUM(CASE WHEN B.PERIODO = '201412' THEN 1 ELSE 0 END) COMPRAM4,
SUM(CASE WHEN B.PERIODO = '201412' THEN A.CANTIDAD ELSE 0 END) CANT_COMPRAM4,
SUM(CASE WHEN B.PERIODO = '201411' THEN 1 ELSE 0 END) COMPRAM5,
SUM(CASE WHEN B.PERIODO = '201411' THEN A.CANTIDAD ELSE 0 END) CANT_COMPRAM5,
SUM(CASE WHEN B.PERIODO = '201410' THEN 1 ELSE 0 END) COMPRAM6,
SUM(CASE WHEN B.PERIODO = '201410' THEN A.CANTIDAD ELSE 0 END) CANT_COMPRAM6
into mkt.DG_recompra_02
FROM 
(
SELECT 
*
FROM  mkt.DG_recompra_01
WHERE PERIODO='201504'--1556
) A
LEFT JOIN 
mkt.DG_recompra_01 B
ON A.PERIODO>B.PERIODO AND A.COD_CLIENTE=B.COD_CLIENTE AND A.COD_PROD=B.COD_PROD
GROUP BY A.PERIODO,A.COD_CLIENTE,A.COD_PROD
ORDER BY 1,2,3 desc


SELECT * FROM mkt.DG_recompra_02
WHERE COD_CLIENTE='000145' AND COD_PROD='352011'

SELECT FECHA,[DESCR_PROD],CANTIDAD FROM  [mkt].[sellout_digalimenta]
WHERE COD_CLIENTE='000145' AND COD_PROD='352011'
ORDER BY 1



ORDER BY 1,2,3 desc


SELECT 
periodo,
COD_CLIENTE CLIENTE,
COD_PROD PROD,
COMPRAM1 RECOMPRA1,
CANT_COMPRAM1 CANT_RECOMPRAM1,
CASE WHEN COMPRAM1+COMPRAM2>1 THEN 1 ELSE 0 END RECOMPRA2,
CANT_COMPRAM1+CANT_COMPRAM2 CANT_RECOMPRAM2,
CASE WHEN COMPRAM1+COMPRAM2+COMPRAM3>1 THEN 1 ELSE 0 END RECOMPRA3,
CANT_COMPRAM1+CANT_COMPRAM2+CANT_COMPRAM3 CANT_RECOMPRAM3,
CASE WHEN COMPRAM1+COMPRAM2+COMPRAM3+COMPRAM4>1 THEN 1 ELSE 0 END RECOMPRA4,
CANT_COMPRAM1+CANT_COMPRAM2+CANT_COMPRAM3+CANT_COMPRAM4 CANT_RECOMPRAM4,
CASE WHEN COMPRAM1+COMPRAM2+COMPRAM3+COMPRAM4+COMPRAM5>1 THEN 1 ELSE 0 END RECOMPRA5,
CANT_COMPRAM1+CANT_COMPRAM2+CANT_COMPRAM3+CANT_COMPRAM4+CANT_COMPRAM5 CANT_RECOMPRAM5,
CASE WHEN COMPRAM1+COMPRAM2+COMPRAM3+COMPRAM4+COMPRAM5+COMPRAM6>1 THEN 1 ELSE 0 END RECOMPRA6,
CANT_COMPRAM1+CANT_COMPRAM2+CANT_COMPRAM3+CANT_COMPRAM4+CANT_COMPRAM5+CANT_COMPRAM6 CANT_RECOMPRAM6
INTO MKT.DG_RECOMPRA
FROM mkt.DG_recompra_02
ORDER BY 2,3




SELECT MAX(FECHA) FROM [mkt].[sellout_digalimenta]


SELECT * FROM  [mkt].[sellout_digalimenta]
WHERE COD_CLIENTE='000145'


352011	ASEPXIA CAMOUFLAGE MAQUILLAJE CJ 12U*28GR