SELECT * FROM [mkt].[SELLOUT_QS_HISTW]


SELECT VBRK_FKDAT,VBRP_MATNR,ZVALNETO_SF_QS,VBRP_FKIMG FROM [mkt].[SELLOUT_QS_HISTW]
WHERE VBRK_KUNAG='0000342327'
ORDER BY VBRK_FKDAT DESC





DECLARE @mydate DATE
DECLARE @mydateini DATE
SELECT @mydate = '20150210';
SELECT @mydateini=dateadd(dd,-day(@mydate)+1,convert(date,@mydate,112));
PRINT(@mydateini);
SELECT 
SUBSTRING(VBRK_FKDAT,1,6) PERIODO,VBRK_KUNAG,sum(VBRP_FKIMG) cantidad
into mkt.QS_recompra_01
FROM [mkt].[SELLOUT_QS_HISTW]
WHERE dateadd(dd,-day(VBRK_FKDAT)+1,convert(date,VBRK_FKDAT,112))<= @mydateini AND 
		dateadd(dd,-day(VBRK_FKDAT)+1,convert(date,VBRK_FKDAT,112))>= dateadd(mm,-6,@mydateini)
		GROUP BY SUBSTRING(VBRK_FKDAT,1,6),VBRK_KUNAG
		ORDER BY 1;


SELECT 
A.PERIODO,A.VBRK_KUNAG,b.periodo,b.VBRK_KUNAG
--SUM(CASE WHEN B.PERIODO = '201501' AND B.CANTIDAD IS not NULL THEN 1 ELSE 0 END) RECOMPRA1
FROM 
(
SELECT 
*
FROM  mkt.QS_recompra_01
WHERE PERIODO='201502'--1556
) A
LEFT JOIN 
mkt.QS_recompra_01 B
ON A.PERIODO>B.PERIODO AND A.VBRK_KUNAG=B.VBRK_KUNAG
--GROUP BY A.PERIODO,A.VBRK_KUNAG
ORDER BY 1,2,3 desc


SELECT 
A.PERIODO,A.VBRK_KUNAG,
SUM(CASE WHEN B.PERIODO = '201501' THEN 1 ELSE 0 END) COMPRAM1,
SUM(CASE WHEN B.PERIODO = '201412' THEN 1 ELSE 0 END) COMPRAM2,
SUM(CASE WHEN B.PERIODO = '201411' THEN 1 ELSE 0 END) COMPRAM3,
SUM(CASE WHEN B.PERIODO = '201410' THEN 1 ELSE 0 END) COMPRAM4,
SUM(CASE WHEN B.PERIODO = '201409' THEN 1 ELSE 0 END) COMPRAM5,
SUM(CASE WHEN B.PERIODO = '201408' THEN 1 ELSE 0 END) COMPRAM6
into mkt.QS_recompra_02
FROM 
(
SELECT 
*
FROM  mkt.QS_recompra_01
WHERE PERIODO='201502'--1556
) A
LEFT JOIN 
mkt.QS_recompra_01 B
ON A.PERIODO>B.PERIODO AND A.VBRK_KUNAG=B.VBRK_KUNAG
GROUP BY A.PERIODO,A.VBRK_KUNAG
ORDER BY 1,2,3 desc


SELECT 
periodo,
VBRK_KUNAG CLIENTE,
COMPRAM1 RECOMPRA1,
CASE WHEN COMPRAM1+COMPRAM2>1 THEN 1 ELSE 0 END RECOMPRA2,
CASE WHEN COMPRAM1+COMPRAM2+COMPRAM3>1 THEN 1 ELSE 0 END RECOMPRA3,
CASE WHEN COMPRAM1+COMPRAM2+COMPRAM3+COMPRAM4>1 THEN 1 ELSE 0 END RECOMPRA4,
CASE WHEN COMPRAM1+COMPRAM2+COMPRAM3+COMPRAM4+COMPRAM5>1 THEN 1 ELSE 0 END RECOMPRA5,
CASE WHEN COMPRAM1+COMPRAM2+COMPRAM3+COMPRAM4+COMPRAM5+COMPRAM6>1 THEN 1 ELSE 0 END RECOMPRA6
FROM mkt.QS_recompra_02







SELECT dateadd(dd,-day(VBRK_FKDAT)+1,convert(date,VBRK_FKDAT,112)) FROM [mkt].[SELLOUT_QS_HISTW]



