
SELECT [ID]
      ,[FECHAGEN]
      ,[VBRP_MATKL]
      ,[VBRP_MATNR]
      ,[WPROD]
      ,[VBRK_KUNAG]
      ,[KNA1_STCD1]
      ,[UBIGEO]
      ,[COD_VEND]
      ,[COD_PROM]
      ,[FREE1]
      ,[COD_OFI]
      ,[COD_CENTRO]
      ,[COD_ALM]
      ,[VBAK_VBELN]
      ,[VBKD_BSARK_E]
      ,[VBRK_VBELN]
      ,[VBRP_POSNR]
      ,[VBRK_XBLNR]
      ,[VBRK_ERDAT]
      ,[VBRK_FKART]
      ,[VBRK_FKDAT]
      ,[VBRK_ZZRFOFI]
      ,[VBRP_CHARG]
      ,[VBRK_ZTERM]
      ,[VBRP_AUGRU_AUFT]
      ,[VBRK_FKSTO]
      ,[VBRP_FKIMG]
	  ,CASE WHEN len([VBRP_FKIMG])=12 THEN CAST(SUBSTRING([VBRP_FKIMG],2,11) AS DECIMAL(12,3))/-1000 ELSE CAST([VBRP_FKIMG] AS DECIMAL(12,3))/1000 END [VBRP_FKIMG]
      ,[VBRP_VRKME]
	  ,CAST([VBRP_ZZ_ZP01] AS DECIMAL(12,2))/100 [VBRP_ZZ_ZP01]
      ,[VBRK_WAERK]
      ,CAST([DESC_RR] AS DECIMAL(6,2))/100 [DESC_RR]
	  ,CAST([DESC_NR] AS DECIMAL(6,2))/100 [DESC_NR]
      ,CASE WHEN len([VBRP_KZWI1])=12 THEN CAST(SUBSTRING([VBRP_KZWI1],2,11) AS DECIMAL(12,2))/-1000 ELSE CAST([VBRP_KZWI1] AS DECIMAL(12,2))/1000 END [VBRP_KZWI1]
	  ,CASE WHEN len([ZVALVTA_UNI])=12 THEN CAST(SUBSTRING([ZVALVTA_UNI],2,11) AS DECIMAL(12,2))/-1000 ELSE CAST([ZVALVTA_UNI] AS DECIMAL(12,2))/1000 END [ZVALVTA_UNI]
	  ,CASE WHEN len([ZIMP_BRUTO])=12 THEN CAST(SUBSTRING([ZIMP_BRUTO],2,11) AS DECIMAL(12,2))/-1000 ELSE CAST([ZIMP_BRUTO] AS DECIMAL(12,2))/1000 END [ZIMP_BRUTO]
      ,CAST([ZMARGEN] AS DECIMAL(6,2))/100 [ZMARGEN]
	  ,CASE WHEN len([ZVAL_VTAIMP])=12 THEN CAST(SUBSTRING([ZVAL_VTAIMP],2,11) AS DECIMAL(12,2))/-1000 ELSE CAST([ZVAL_VTAIMP] AS DECIMAL(12,2))/1000 END [ZVAL_VTAIMP]
      ,CASE WHEN len([ZIMP_IMPTO])=12 THEN CAST(SUBSTRING([ZIMP_IMPTO],2,11) AS DECIMAL(12,2))/-1000 ELSE CAST([ZIMP_IMPTO] AS DECIMAL(12,2))/1000 END [ZIMP_IMPTO]
      ,CAST([DESC_QS] AS DECIMAL(6,2))/100 [DESC_QS]
      ,CASE WHEN len([ZVALNETO])=12 THEN CAST(SUBSTRING([ZVALNETO],2,11) AS DECIMAL(12,2))/-1000 ELSE CAST([ZVALNETO] AS DECIMAL(12,2))/1000 END [ZVALNETO]
      ,[CLS_PED]
      ,[IND_BONIF]
	  ,CASE WHEN len([ZVALNET_CFLETE])=12 THEN CAST(SUBSTRING([ZVALNET_CFLETE],2,11) AS DECIMAL(12,2))/-1000 ELSE CAST([ZVALNET_CFLETE] AS DECIMAL(12,2))/1000 END [ZVALNET_CFLETE]
	  ,CASE WHEN len([VAL_DESC_RR])=12 THEN CAST(SUBSTRING([VAL_DESC_RR],2,11) AS DECIMAL(12,2))/-1000 ELSE CAST([VAL_DESC_RR] AS DECIMAL(12,2))/1000 END [VAL_DESC_RR]
      ,CASE WHEN len([VAL_DESC_NR])=12 THEN CAST(SUBSTRING([VAL_DESC_NR],2,11) AS DECIMAL(12,2))/-1000 ELSE CAST([VAL_DESC_NR] AS DECIMAL(12,2))/1000 END [VAL_DESC_NR]
	  ,CASE WHEN len([VAL_DESC_QS])=12 THEN CAST(SUBSTRING([VAL_DESC_QS],2,11) AS DECIMAL(12,2))/-1000 ELSE CAST([VAL_DESC_QS] AS DECIMAL(12,2))/1000 END [VAL_DESC_QS]
	  ,CASE WHEN len([VAL_FLETE_APROV])=12 THEN CAST(SUBSTRING([VAL_FLETE_APROV],2,11) AS DECIMAL(12,2))/-1000 ELSE CAST([VAL_FLETE_APROV] AS DECIMAL(12,2))/1000 END [VAL_FLETE_APROV]
      ,CASE WHEN len([ZVALNETO_SF_QS])=12 THEN CAST(SUBSTRING([ZVALNETO_SF_QS],2,11) AS DECIMAL(12,2))/-1000 ELSE CAST([ZVALNETO_SF_QS] AS DECIMAL(12,2))/1000 END [ZVALNETO_SF_QS]
      ,CAST([TIPO_CAMBIO] AS DECIMAL(12,5))/100000 [DESC_NR]
      ,CAST([PJE_DSCTO_CE] AS DECIMAL(5,2))/100 [PJE_DSCTO_CE]
	  ,CASE WHEN len([VALOR_DSCTO_CE])=12 THEN CAST(SUBSTRING([VALOR_DSCTO_CE],2,11) AS DECIMAL(12,2))/-1000 ELSE CAST([VALOR_DSCTO_CE] AS DECIMAL(12,2))/1000 END [VALOR_DSCTO_CE]
      ,CASE WHEN len([COSTO_UNIT])=12 THEN CAST(SUBSTRING([COSTO_UNIT],2,11) AS DECIMAL(12,2))/-1000 ELSE CAST([COSTO_UNIT] AS DECIMAL(12,2))/1000 END [COSTO_UNIT]
      ,[ORG_VTAS]
      ,[SECTOR]
      ,[CARACT_NEG]
      ,[TRAT_COMERCIAL]
  FROM [genomma].[mkt].[sellout_qui_suiza]


SELECT FECHAGEN,COUNT(1) FROM MKT.SELLOUT_QS_HIST
GROUP BY FECHAGEN
ORDER BY 1

SELECT  substring(VBRK_FKDAT,1,6) ,COUNT(1)  FROM MKT.SELLOUT_QS_HIST
GROUP BY substring(VBRK_FKDAT,1,6)
ORDER BY  1


SELECT min(VBRK_FKDAT),max(VBRK_FKDAT) FROM MKT.SELLOUT_QS_HIST

SELECT min(VBRK_FKDAT),max(VBRK_FKDAT) FROM MKT.SELLOUT_QS_HIST_2

insert into MKT.SELLOUT_QS_HIST
SELECT * FROM MKT.SELLOUT_QS_HIST_2

SELECT COUNT(1)  FROM MKT.SELLOUT_QS_HIST

SELECT * FROM [mkt].[stock_qui_suiza_ex]














