SELECT * FROM  [mkt].[sellout_qs_day]

SELECT * FROM   mkt.stock_qs_day

SELECT MAX(FECHA) FROM  per.SELLOUT_QS




SELECT FECHA,COUNT(1)  FROM [mkt].[STOCK_QS_HISTW]
GROUP BY FECHA ORDER BY 1 DESC

SELECT * FROM [mkt].[STOCK_QS_HIST]

SELECT codigo_sap,COUNT(1) FROM MKT.[STOCK_QS_HIST]
WHERE codigo_sap NOT IN
(SELECT PROIDCLIE FROM MKT.maestro_FUENTE_producto)
GROUP BY codigo_sap
/*
codigo_sap	(No column name)
116854	168*/

SELECT VBRP_MATNR,COUNT(1),sum(VBRP_FKIMG),sum(ZVALNETO_SF_QS) FROM MKT.SELLOUT_QS_HISTW
WHERE VBRP_MATNR NOT IN
(SELECT PROIDCLIE FROM MKT.maestro_FUENTE_producto)
GROUP BY VBRP_MATNR

/*
VBRP_MATNR	(No column name)	(No column name)	(No column name)
186271	1	0.00000000	-42.790000
116854	102	325.00000000	5102.370000
*/


SELECT COUNT(1)  FROM PER.SELLOUT_QS;--269977

insert into [per].MAESTRO_PRODUCTO_PRECIO
SELECT 
NEXT VALUE FOR [per].[seq_precioid] OVER(ORDER BY [GrpID],[ProPstID],AÒoSemana_GL),
A.*
FROM 
(
SELECT 
'307' GRPID,PROPSTID,AÒoSemana_GL,0 PRECIO FROM
(
SELECT Q.PROPSTID,Q.AÒoSemana_GL FROM
(
SELECT DISTINCT B.PROPSTID,T.AÒoSemana_GL FROM
(
SELECT * FROM 
MKT.STOCK_QS_HISTW 
WHERE CODIGO_SAP<>'116854'
) A
LEFT JOIN per.MAESTRO_PRODUCTO_FUENTE B
ON A.Codigo_SAP=B.PROIDCLIE
LEFT JOIN per.MAESTRO_TIEMPO T
ON A.FECHA=T.Fecha
) Q LEFT JOIN per.MAESTRO_PRODUCTO_PRECIO H
ON H.GrpID='307' AND H.AÒOSEMANA_GL=Q.AÒoSemana_GL AND H.ProPstID=Q.PROPSTID
WHERE H.PrecioLista IS NULL 
) P
) A;



DROP TABLE [per].[STOCK_QS]
SELECT 
D.Fecha,
B.ProPstID,
C.CadenaID,
H.PrecioID,
SUM(A.CANT_01) UnidCedis,
SUM(A.CANT_02) UnidTrans,
D.AÒoSemana_GL
INTO [per].[STOCK_QS]
FROM 
(
SELECT * FROM 
MKT.STOCK_QS_HISTW 
WHERE CODIGO_SAP<>'116854'
) A
LEFT JOIN per.MAESTRO_PRODUCTO_FUENTE B
ON A.CODIGO_SAP=B.ProIDClie AND B.GrpID='307'
LEFT JOIN per.MAESTRO_CADENA C
ON A.CD_CENTRO=C.CadenaIDClie
LEFT JOIN per.MAESTRO_TIEMPO D
ON D.Fecha=A.FECHA
LEFT JOIN per.[maestro_producto_precio] H
ON H.GrpID='307' AND H.AÒOSEMANA_GL=D.AÒoSemana_GL AND H.ProPstID=B.ProPstID
GROUP BY 
D.Fecha,
B.ProPstID,
C.CadenaID,
H.PrecioID,
D.AÒoSemana_GL

SELECT * FROM [per].[STOCK_QS]
WHERE AÒoSemana_GL IS NULL


truncate TABLE [per].[INFO_QUIMICASUIZA];
insert into [per].[INFO_QUIMICASUIZA]
SELECT * FROM 
(
SELECT 
A.Fecha,
A.CadenaID,
A.OficinaID,
A.GrupoTratID,
A.VendedorID,
A.ProPstID,
A.PdvID,
A.PrecioID,
A.UnidDesp,
A.MontoDespCliente,
A.MontoDesp,
B.UnidCedis,
B.UnidTrans 
FROM PER.SELLOUT_QS A
LEFT JOIN 
(
SELECT * FROM 
PER.STOCK_QS
WHERE 1=2) B
ON A.ProPstID=B.PROPSTID
UNION ALL
SELECT 
B.Fecha,
B.CadenaID,
NULL,
NULL,
NULL,
B.ProPstID,
NULL,
B.PrecioID,
NULL,
NULL,
NULL,
B.UnidCedis,
B.UnidTrans 
FROM PER.STOCK_QS B
LEFT JOIN 
(
SELECT * FROM 
PER.SELLOUT_QS
WHERE 1=2) A
ON A.ProPstID=B.ProPstID
) A




SELECT MIN(FECHA),MAX(FECHA) FROM PER.SELLOUT_QS 
SELECT MIN(FECHA),MAX(FECHA) FROM PER.Stock_QS 

SELECT * FROM PER.SELLOUT_QS A
WHERE A.Fecha='20150522'


SELECT COUNT(1)  FROM PER.STOCK_QS
SELECT COUNT(1)  FROM PER.SELLOUT_QS 


SELECT COUNT(1)  FROM PER.SO_ST_QUIMICASUIZA 


DROP TABLE mkt.sellout_inka;
DROP TABLE mkt.stock_inka;


SELECT periodo,total FROM
(
SELECT periodo,COUNT(1)  total FROM mkt.sellout_inka
GROUP BY periodo
ORDER BY 1
) a
ORDER BY 2 desc


ORDER BY 1

SELECT min(periodo),max(periodo) FROM mkt.sellout_inka


SELECT fecha,COUNT(1)  total FROM mkt.stock_inka
GROUP BY fecha
ORDER BY 1



SELECT * FROM mkt.stock_inka