DROP TABLE  mkt.IBOPE_CPT_HISTW
SELECT
  CAST(MEDIO AS VARCHAR(2)) MEDIO,
  CAST(EMISORA AS VARCHAR(20)) EMISORA,
  CAST(PROGRAMA AS VARCHAR(100)) PROGRAMA,
  CAST(GENERO AS VARCHAR(30)) GENERO,
  CAST(SUBSTRING(DIA,1,4)+SUBSTRING(DIA,6,2)+SUBSTRING(DIA,9,2) AS VARCHAR(10)) DIA,
  CAST(MARCA AS VARCHAR(20)) MARCA,
  CAST(ANUNCIANTE AS VARCHAR(20)) ANUNCIANTE,
  CAST(CATEGORIA AS VARCHAR(50)) CATEGORIA,
  CAST(PRODUCTO AS VARCHAR(50)) PRODUCTO,
  CAST(TIPO AS VARCHAR(30)) TIPO,
  CAST(VERSION AS VARCHAR(30)) VERSION,
  CAST(CAST(REPLACE(RTRIM(LTRIM(SPOTS)),',','.') AS DECIMAL(6,0)) AS INTEGER) SPOTS,
  CAST(HORA AS VARCHAR(25)) HORA,
  CAST(BLOQUE AS VARCHAR(25)) BLOQUE,
  CAST(CAST(REPLACE(RTRIM(LTRIM(DUR_T)),',','.') AS DECIMAL(6,0)) AS INTEGER) DUR_T,
  CAST(PAG_POS AS VARCHAR(5)) PAG_POS,
  CAST(POS_SPOT AS VARCHAR(25)) POS_SPOT,
  CAST(CAST(REPLACE(RTRIM(LTRIM(BRK)),',','.') AS DECIMAL(6,0)) AS INTEGER) BRK,
  CAST(REPLACE(RTRIM(LTRIM(TARIFA)),',','.') AS DECIMAL(7,2)) TARIFA,
  COALESCE(TRY_CAST(REPLACE(RTRIM(LTRIM(TOTAL_TELE)),',','.') AS DECIMAL(7,2)),0) TOTAL_TELE,
  COALESCE(TRY_CAST(REPLACE(RTRIM(LTRIM(TOTAL_AMAS)),',','.') AS DECIMAL(7,2)),0) TOTAL_AMAS,
  COALESCE(TRY_CAST(REPLACE(RTRIM(LTRIM(HYM12A25)),',','.') AS DECIMAL(7,2)),0) HYM12A25,
  COALESCE(TRY_CAST(REPLACE(RTRIM(LTRIM(M12A25)),',','.') AS DECIMAL(7,2)),0) M12A25,
  COALESCE(TRY_CAST(REPLACE(RTRIM(LTRIM(M18)),',','.') AS DECIMAL(7,2)),0) M18,
  COALESCE(TRY_CAST(REPLACE(RTRIM(LTRIM(HYM18)),',','.') AS DECIMAL(7,2)),0) HYM18,
  COALESCE(TRY_CAST(REPLACE(RTRIM(LTRIM(HYM25)),',','.') AS DECIMAL(7,2)),0) HYM25,
  COALESCE(TRY_CAST(REPLACE(RTRIM(LTRIM(M25)),',','.') AS DECIMAL(7,2)),0) M25,
  COALESCE(TRY_CAST(REPLACE(RTRIM(LTRIM(M12)),',','.') AS DECIMAL(7,2)),0) M12,
  CAST(ARCHIVO AS VARCHAR(30)) ARCHIVO
INTO mkt.IBOPE_CPT_HISTW
FROM mkt.IBOPE_CPT_HIST;

SELECT * FROM mkt.IBOPE_CPT_HISTW

SELECT DISTINCT dia FROM mkt.IBOPE_CPT_HIST;
SELECT * FROM mkt.IBOPE_CPT_HIST;