/*QUIMICA SUIZA*/
SELECT DISTINCT a.GrpID,a.ProIDClie,NULL ProPstNombreClie FROM
(
SELECT * FROM per.MAESTRO_PRODUCTO_FUENTE
WHERE ProPstID='0000'
AND GrpID='307'
) A
/*CONTINENTAL*/
SELECT DISTINCT a.GrpID,a.ProIDClie,COALESCE(B.DESC_PROD,C.DESC_PRODUCTO) ProPstNombreClie FROM
(
SELECT * FROM per.MAESTRO_PRODUCTO_FUENTE
WHERE ProPstID='0000'
AND GrpID='327'
) A LEFT JOIN mkt.SELLOUT_CONTI_HISTW B
  ON A.ProIDClie=CONVERT(VARCHAR,CONVERT(BIGINT,B.PRODUCTO))
LEFT JOIN mkt.STOCK_CONTI_HISTW C
  ON A.ProIDClie=CONVERT(VARCHAR,CONVERT(BIGINT,C.CODIGO))
/*DIGALIMENTA*/
SELECT DISTINCT a.GrpID,a.ProIDClie,COALESCE(B.DESCR_PROD,C.Producto) ProPstNombreClie FROM
(
SELECT * FROM per.MAESTRO_PRODUCTO_FUENTE
WHERE ProPstID='0000'
AND GrpID='337'
) A LEFT JOIN mkt.SELLOUT_DIGA_HISTW B
  ON A.ProIDClie=CONVERT(VARCHAR,CONVERT(BIGINT,B.COD_PROD))
LEFT JOIN mkt.STOCK_DIGA_HISTW C
  ON A.ProIDClie=CONVERT(VARCHAR,CONVERT(BIGINT,C.CodProducto))
/*KEYMARK*/
SELECT DISTINCT a.GrpID,a.ProIDClie,COALESCE(B.NOMPRODUCTO,C.NOMPRODUCTO) ProPstNombreClie FROM
(
SELECT * FROM per.MAESTRO_PRODUCTO_FUENTE
WHERE ProPstID='0000'
AND GrpID='338'
) A LEFT JOIN mkt.SELLOUT_KEYMARK_HISTW B
  ON A.ProIDClie=COALESCE(CAST(try_CONVERT(BIGINT,B.COD_PRODUCTO) AS VARCHAR(12)),B.COD_PRODUCTO)
LEFT JOIN mkt.STOCK_KEYMARK_HISTW C
  ON A.ProIDClie=COALESCE(CAST(try_CONVERT(BIGINT,C.COD_PRODUCTO) AS VARCHAR(12)),C.COD_PRODUCTO)
/*INKAFARMA*/

SELECT A.GrpID,A.ProIDClie,B.DESCRIPCION ProPstNombreClie,TAG FROM
(
SELECT * FROM per.MAESTRO_PRODUCTO_FUENTE
WHERE ProPstID='0000'
AND GrpID='309'
) A LEFT JOIN (
SELECT
    CAST(COD_PRODUCTO AS VARCHAR(15)) COD_PRODUCTO,
    MAX(DESCRIPCION) DESCRIPCION,
  MAX(TAG) TAG
  --INTO MKT.PROD_INKA
  FROM
    (
      SELECT DISTINCT
        COALESCE(CONVERT(VARCHAR, TRY_CONVERT(BIGINT, COD_PRODUCTO)), COD_PRODUCTO) COD_PRODUCTO,
        DESCRIPCION,
        'SOW' TAG
      FROM mkt.SELLOUT_IK_HISTW
      UNION ALL
      SELECT DISTINCT
        COALESCE(CONVERT(VARCHAR, TRY_CONVERT(BIGINT, Cod)), Cod) COD_PRODUCTO,
        Producto,
        'SOA'
      FROM mkt.SELLOUT_IK_HISTA
      UNION ALL
      SELECT DISTINCT
        COALESCE(CONVERT(VARCHAR, TRY_CONVERT(BIGINT, COD_SAP)), COD_SAP) COD_PRODUCTO,
        DESCRIPCION_PRODUCTO,
        'STW'
      FROM mkt.STOCK_IK_HISTW
    ) A
  GROUP BY COD_PRODUCTO
  ) B
  ON A.ProIDClie=B.COD_PRODUCTO;
/*ALBIS*/
SELECT DISTINCT a.GrpID,a.ProIDClie,COALESCE(B.Desc_Producto,C.Desc_Producto) ProPstNombreClie FROM
(
SELECT * FROM per.MAESTRO_PRODUCTO_FUENTE
WHERE ProPstID='0000'
AND GrpID='311'
) A LEFT JOIN mkt.SELLOUT_ALBIS_HISTW B
  ON A.ProIDClie=COALESCE(CONVERT(VARCHAR,TRY_CONVERT(BIGINT,B.Cod_Producto)),B.Cod_Producto)
LEFT JOIN mkt.STOCK_ALBIS_HISTW C
  ON A.ProIDClie=COALESCE(CONVERT(VARCHAR,TRY_CONVERT(BIGINT,C.Cod_Producto)),C.Cod_Producto)
/*SUPESA*/
SELECT DISTINCT a.GrpID,a.ProIDClie,COALESCE(B.DESCRIPCION,C.DESCRIPCION) ProPstNombreClie FROM
(
SELECT * FROM per.MAESTRO_PRODUCTO_FUENTE
WHERE ProPstID='0000'
AND GrpID='308'
) A LEFT JOIN mkt.SELLOUT_SPP_HISTW B
  ON A.ProIDClie=COALESCE(CONVERT(VARCHAR,TRY_CONVERT(BIGINT,B.COD_SPSA)),B.COD_SPSA)
LEFT JOIN mkt.STOCK_SPP_HISTW C
  ON A.ProIDClie=COALESCE(CONVERT(VARCHAR,TRY_CONVERT(BIGINT,C.COD_SPSA)),C.COD_SPSA);
/*CENCOSUD*/
SELECT DISTINCT a.GrpID,a.ProIDClie,COALESCE(B.DESCRIPCION,C.DESCRIPCION) ProPstNombreClie FROM
(
SELECT * FROM per.MAESTRO_PRODUCTO_FUENTE
WHERE ProPstID='0000'
AND GrpID='328'
) A LEFT JOIN mkt.SELLOUT_CENCO_HISTW B
  ON A.ProIDClie=COALESCE(CONVERT(VARCHAR,TRY_CONVERT(BIGINT,B.COD_CENCOSUD)),B.COD_CENCOSUD)
LEFT JOIN mkt.STOCK_CENCO_HISTW C
  ON A.ProIDClie=COALESCE(CONVERT(VARCHAR,TRY_CONVERT(BIGINT,C.COD_CENCOSUD)),C.COD_CENCOSUD)
/*TOTTUS*/
SELECT DISTINCT a.GrpID,a.ProIDClie,COALESCE(B.DESC_PDV,NULL) ProPstNombreClie FROM
(
SELECT * FROM per.MAESTRO_PRODUCTO_FUENTE
WHERE ProPstID='0000'
AND GrpID='312'
) A LEFT JOIN mkt.SELLOUT_TOTTUS_HISTW B
  ON A.ProIDClie=COALESCE(CONVERT(VARCHAR,TRY_CONVERT(BIGINT,B.COD_PDV)),B.COD_PDV)
--LEFT JOIN mkt.STOCK_TOTTUS_HISTW C
  --ON A.ProIDClie=COALESCE(CONVERT(VARCHAR,TRY_CONVERT(BIGINT,C.COD_CENCOSUD)),C.COD_CENCOSUD)
/*QUIMIZA*/
SELECT DISTINCT a.GrpID,a.ProIDClie,NULL ProPstNombreClie FROM
(
SELECT * FROM per.MAESTRO_PRODUCTO_FUENTE
WHERE ProPstID='0000'
AND GrpID='313'
) A