SELECT * INTO PER.SELLOUT_QS FROM MKT.SO_QS_FINAL

SELECT VBRK_FKDAT,COUNT(1)  FROM mkt.sellout_qs_day
GROUP BY VBRK_FKDAT
ORDER BY 1

DROP TABLE per.MAESTRO_TIEMPO;
SELECT * into per.MAESTRO_TIEMPO FROM mkt.MAESTRO_TIEMPO


DROP TABLE MKT.SO_QS_SUM;
SELECT 
VBRK_FKDAT	,
COD_CENTRO	,
COD_OFI	,
TRAT_COMERCIAL	,
VBRK_KUNAG	,
COD_VEND	,
VBRP_MATNR,
SUM(VBRP_FKIMG) CANTIDAD,
SUM(ZVALNETO_SF_QS) MONTO
INTO MKT.SO_QS_SUM
FROM 
[mkt].[SELLOUT_QS_HISTW]
GROUP BY 
VBRK_FKDAT	,
COD_CENTRO	,
COD_OFI	,
TRAT_COMERCIAL	,
VBRK_KUNAG	,
COD_VEND	,
VBRP_MATNR

SELECT VBRP_MATNR,COUNT(1),sum(cantidad),sum(monto) FROM MKT.SO_QS_SUM
WHERE VBRP_MATNR NOT IN
(SELECT PROIDCLIE FROM MKT.maestro_FUENTE_producto)
GROUP BY VBRP_MATNR
/*
VBRP_MATNR	(No column name)	(No column name)	(No column name)
186271	1	0.00000000	-42.790000
116854	97	325.00000000	5102.370000
*/

DELETE FROM MKT.SO_QS_SUM
WHERE VBRP_MATNR NOT IN
(SELECT PROIDCLIE FROM MKT.maestro_FUENTE_producto)



DELETE FROM PER.SELLOUT_QS;
INSERT INTO PER.SELLOUT_QS
SELECT 
A.VBRK_FKDAT FECHA,
B.CADENAID,
C.OFICINAID,
D.Grupo1ID,
F.VENDEDORID,
PP.ProPstID,
PD.PDVID,
H.PRECIOID,
A.CANTIDAD UNIDDESP,
A.MONTO MONTODESPCLIENTE,
A.CANTIDAD*H.PrecioLista MONTODESP,
T.AÒoSemana_GL
FROM MKT.SO_QS_SUM A
LEFT JOIN per.[maestro_cadena] B
ON A.COD_CENTRO=B.CadenaIDClie
LEFT JOIN per.[maestro_OFICINA] C
ON A.COD_OFI=C.OficinaIDClie
LEFT JOIN per.[MAESTRO_GRUPO1] D
ON A.TRAT_COMERCIAL=D.Grupo1IDClie
LEFT JOIN per.[maestro_vendedor] F
ON A.COD_VEND=F.VendedorIDClie
LEFT JOIN per.[maestro_tiempo] T
ON A.VBRK_FKDAT=T.Fecha
LEFT JOIN per.maestro_producto_fuente G
ON G.[GrpID]='307' AND A.VBRP_MATNR=G.PROIDCLIE
LEFT JOIN per.[maestro_producto_presentacion] PP
ON G.PROPSTID=PP.PROPSTID
LEFT JOIN per.[maestro_producto_precio] H
ON H.GrpID='307' AND H.AÒOSEMANA_GL=T.AÒoSemana_GL AND H.ProPstID=G.PROPSTID
LEFT JOIN per.maestro_pdv PD
ON CONVERT(VARCHAR,CONVERT(INTEGER,VBRK_KUNAG))=PD.PdvIDClie AND PD.GrpID='307';

/*
SELECT * INTO MKT.SO_QS_BACK FROM [per].[SELLOUT_QS]
*/


SELECT * FROM PER.SELLOUT_QS
WHERE GrupoTratID IS NULL 

insert into [per].MAESTRO_PRODUCTO_PRECIO
SELECT 
NEXT VALUE FOR [per].[seq_precioid] OVER(ORDER BY [GrpID],[ProPstID],AÒoSemana_GL),
A.*
FROM 
(
SELECT 
'307' GRPID,PROPSTID,AÒoSemana_GL,0 PRECIO FROM
(
SELECT Q.PROPSTID,Q.AÒoSemana_GL FROM
(
SELECT DISTINCT B.PROPSTID,T.AÒoSemana_GL FROM
MKT.SO_QS_SUM A
LEFT JOIN per.MAESTRO_PRODUCTO_FUENTE B
ON A.VBRP_MATNR=B.PROIDCLIE
LEFT JOIN per.MAESTRO_TIEMPO T
ON A.VBRK_FKDAT=T.Fecha
) Q LEFT JOIN per.MAESTRO_PRODUCTO_PRECIO H
ON H.GrpID='307' AND H.AÒOSEMANA_GL=Q.AÒoSemana_GL AND H.ProPstID=Q.PROPSTID
WHERE H.PrecioLista IS NULL 
) P
) A;