DELETE FROM mkt.so_qs_2;

insert INTO mkt.so_qs_2
SELECT 
VBRK_FKDAT	,
COD_CENTRO	,
COD_OFI	,
TRAT_COMERCIAL	,
VBRK_KUNAG	,
COD_VEND	,
VBRP_MATNR,
SUM(VBRP_FKIMG) CANTIDAD,
SUM(ZVALNETO_SF_QS) MONTO
FROM 
(
SELECT * FROM 
MKT.SELLOUT_QS_HISTW
WHERE 
VBRP_MATNR not in ('186271','116854')
) a
GROUP BY 
VBRK_FKDAT	,
COD_CENTRO	,
COD_OFI	,
TRAT_COMERCIAL	,
VBRK_KUNAG	,
COD_VEND	,
VBRP_MATNR;


/*CHECK PRESENTACION PRODUCTO*/

--SELECT * FROM per.maestro_fuente_producto

insert into per.MAESTRO_PRODUCTO_FUENTE
SELECT 
VBRP_MATNR,
'307' GRPID,
'0000' PROPSTID
FROM
(
SELECT DISTINCT VBRP_MATNR FROM mkt.so_qs_2 a
LEFT JOIN [per].MAESTRO_PRODUCTO_FUENTE B
ON A.VBRP_MATNR=B.PROIDCLIE AND B.GrpID='307'
WHERE B.PROPSTID IS NULL 
) A;




/*CHECK PDV*/
print ('validaciones')
insert into [per].maestro_pdv
SELECT 
NEXT VALUE FOR per.seq_PDVid OVER(ORDER BY VBRK_KUNAG),
	VBRK_KUNAG,
	VBRK_KUNAG,
	VBRK_KUNAG,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	'307'
FROM 
(
SELECT DISTINCT CONVERT(VARCHAR,CONVERT(INTEGER,VBRK_KUNAG)) VBRK_KUNAG  FROM MKT.so_qs_2 A
LEFT JOIN [per].maestro_pdv PD
ON CONVERT(VARCHAR,CONVERT(INTEGER,VBRK_KUNAG))=PD.PdvIDClie AND PD.GrpID='307'
WHERE PDVID IS NULL 
) A;


/*CHECK CADENAID*/

insert into [per].[maestro_cadena]
SELECT 
NEXT VALUE FOR per.seq_cadenaid OVER(ORDER BY [COD_CENTRO]),
[COD_CENTRO],
[COD_CENTRO],
'307'
FROM 
(
SELECT DISTINCT COD_CENTRO FROM MKT.so_qs_2 a
LEFT JOIN [per].[maestro_cadena] B
ON A.COD_CENTRO=B.CadenaIDClie AND A.GrpID='307'
WHERE B.CADENAID IS NULL 
) A;

/*CHECK OFICINAID*/

insert into [per].[maestro_oficina]
SELECT 
NEXT VALUE FOR per.seq_oficinaid OVER(ORDER BY COD_OFI),
COD_OFI,
COD_OFI,
'307'
FROM 
(
SELECT DISTINCT COD_OFI FROM mkt.so_qs_2 a
LEFT JOIN [per].[maestro_oficina] B
ON A.COD_OFI=B.OficinaIDClie
WHERE B.OFICINAID IS NULL 
) A;

/*CHECK TARGETGROUP*/

insert into [per].MAESTRO_GRUPO1
SELECT 
NEXT VALUE FOR [per].[seq_Grupo1id] OVER(ORDER BY TRAT_COMERCIAL),
TRAT_COMERCIAL,
TRAT_COMERCIAL,
'307'
FROM 
(
SELECT DISTINCT TRAT_COMERCIAL FROM mkt.so_qs_2 a
LEFT JOIN [per].MAESTRO_GRUPO1 B
ON A.TRAT_COMERCIAL=B.Grupo1IDClie
WHERE B.Grupo1ID IS NULL 
) A;

/*CHECK VENDEDOR*/

insert into [per].[maestro_vendedor]
SELECT 
NEXT VALUE FOR [per].[seq_vendedorid] OVER(ORDER BY COD_VEND),
COD_VEND,
COD_VEND,
'307'
FROM 
(
SELECT DISTINCT COD_VEND FROM mkt.so_qs_2 a
LEFT JOIN [per].[maestro_vendedor] B
ON A.COD_VEND=B.VendedorIDClie
WHERE B.VENDEDORID IS NULL 
) A;

/*CHECK PRECIO*/

insert into [per].MAESTRO_PRODUCTO_PRECIO
SELECT 
NEXT VALUE FOR [per].[seq_precioid] OVER(ORDER BY [GrpID],[ProPstID],AÒoSemana_GL),
A.*
FROM 
(
SELECT 
'307' GRPID,PROPSTID,AÒoSemana_GL,0 PRECIO FROM
(
SELECT Q.PROPSTID,Q.AÒoSemana_GL FROM
(
SELECT DISTINCT B.PROPSTID,T.AÒoSemana_GL FROM
mkt.so_qs_2 A
LEFT JOIN per.MAESTRO_PRODUCTO_FUENTE B
ON A.VBRP_MATNR=B.PROIDCLIE
LEFT JOIN per.MAESTRO_TIEMPO T
ON A.VBRK_FKDAT=T.Fecha
) Q LEFT JOIN per.MAESTRO_PRODUCTO_PRECIO H
ON H.GrpID='307' AND H.AÒOSEMANA_GL=Q.AÒoSemana_GL AND H.ProPstID=Q.PROPSTID
WHERE H.PrecioLista IS NULL 
) P
) A;

--DROP TABLE mkt.so_qs_3;
DELETE FROM mkt.so_qs_3;
insert INTO mkt.so_qs_3
SELECT 
A.VBRK_FKDAT Fecha,
'307' GrpID,
B.CadenaID,
C.OficinaID,
D.Grupo1ID GrupoTratID,
F.VendedorID,
S.SupervisorID,
PP.ProPstID,
PD.PdvID,
H.PrecioID,
A.CANTIDAD UnidDesp,
A.MONTO MontoDespCliente,
A.CANTIDAD*H.PrecioLista MontoDesp,
T.AÒoSemana_GL
FROM mkt.so_qs_2 A
LEFT JOIN per.[maestro_cadena] B
ON A.COD_CENTRO=B.CadenaIDClie AND B.GrpID='307'
LEFT JOIN per.[maestro_OFICINA] C
ON A.COD_OFI=C.OficinaIDClie AND C.GrpID='307'
LEFT JOIN per.[MAESTRO_GRUPO1] D
ON A.TRAT_COMERCIAL=D.Grupo1IDClie AND D.GrpID='307'
LEFT JOIN per.[maestro_vendedor] F
ON A.COD_VEND=F.VendedorIDClie AND F.GrpID='307'
LEFT JOIN per.[maestro_supervisor] S
ON NULL=S.SupervisorIDClie AND S.GrpID='307'
LEFT JOIN per.[maestro_tiempo] T
ON A.VBRK_FKDAT=T.Fecha
LEFT JOIN per.maestro_producto_fuente G
ON A.VBRP_MATNR=G.PROIDCLIE AND G.[GrpID]='307'
LEFT JOIN per.[maestro_producto_presentacion] PP
ON G.PROPSTID=PP.PROPSTID
LEFT JOIN per.[maestro_producto_precio] H
ON H.AÒOSEMANA_GL=T.AÒoSemana_GL AND H.ProPstID=G.PROPSTID AND H.GrpID='307'
LEFT JOIN per.maestro_pdv PD
ON CONVERT(VARCHAR,CONVERT(INTEGER,VBRK_KUNAG))=PD.PdvIDClie AND PD.GrpID='307';

--DROP TABLE [per].[SELLOUT_QS];

DELETE FROM [per].[SELLOUT_QS];

insert into [per].[SELLOUT_QS]
SELECT * FROM mkt.so_qs_3;
