DROP TABLE MKT.SO_QS_SUM

SELECT 
VBRK_FKDAT	,
COD_CENTRO	,
COD_OFI	,
TRAT_COMERCIAL	,
VBRK_KUNAG	,
COD_VEND	,
VBRP_MATNR,
SUM(VBRP_FKIMG) CANTIDAD,
SUM(ZVALNETO_SF_QS) MONTO
INTO MKT.SO_QS_SUM
FROM 
[mkt].[SELLOUT_QS_HISTW]
GROUP BY 
VBRK_FKDAT	,
COD_CENTRO	,
COD_OFI	,
TRAT_COMERCIAL	,
VBRK_KUNAG	,
COD_VEND	,
VBRP_MATNR

SELECT COUNT(*) FROM MKT.SO_QS_SUM;--264982




/*ELIMINANDO REGISTROS*/

SELECT VBRP_MATNR,COUNT(1),sum(cantidad),sum(monto) FROM MKT.SO_QS_SUM
WHERE VBRP_MATNR NOT IN
(SELECT PROIDCLIE FROM MKT.maestro_FUENTE_producto)
GROUP BY VBRP_MATNR

/*
VBRP_MATNR	(No column name)	(No column name)	(No column name)
186271	1	0.00000000	-42.790000
116854	97	325.00000000	5102.370000
*/

DELETE FROM MKT.SO_QS_SUM
WHERE VBRP_MATNR NOT IN
(SELECT PROIDCLIE FROM MKT.maestro_FUENTE_producto)

SELECT COUNT(*) FROM MKT.SO_QS_SUM;--264884


SELECT COD_VEND,COUNT(1) VECES ,SUM(A.CANTIDAD) CANTIDAD_VENDIDA,MAX(VBRK_FKDAT) MAXFECHA,MIN(VBRK_FKDAT) MINFECHA FROM MKT.SO_QS_SUM a
WHERE COD_VEND NOT IN
(SELECT COD_VENDEDOR FROM MKT.[maestro_vendedor])
GROUP BY COD_VEND
/*
COD_VEND	VECES	CANTIDAD_VENDIDA	MAXFECHA	MINFECHA
19489	184	461.00000000	20150509	20150408
19668	23	142.00000000	20150507	20150507
19690	62	314.00000000	20150509	20150430
19622	19	104.00000000	20150425	20150411

*/


SELECT COUNT(DISTINCT VBRK_KUNAG)  FROM MKT.SO_QS_SUM
WHERE VBRK_KUNAG NOT IN
(SELECT COD_PDV FROM MKT.maestro_pdv);--4750


/*COMPROBANDO NULLS*/


DROP TABLE MKT.PRUEBA_QS;

SELECT 
A.VBRK_FKDAT FECHA,
B.CADENAID,
B.DESC_CADENA,
C.OFICINAID,
C.DESC_OFICINA,
D.GRUPOTARGETID,
D.DESC_GRUPOTARGET,
F.VENDEDORID,
F.DESC_VENDEDOR,
PP.ProPstID,
PP.ProPstNombre,
PD.PDVID,
PD.PDVNOMBRE,
A.VBRK_KUNAG,
A.CANTIDAD UNIDDESP,
A.MONTO MONTODESPCLIENTE,
A.CANTIDAD*H.PRECIO_LISTA MONTODESP,
H.PRECIOID,
T.AÒoSemana_GL
INTO MKT.PRUEBA_QS
FROM MKT.SO_QS_SUM A
LEFT JOIN [mkt].[maestro_cadena] B
ON A.COD_CENTRO=B.COD_CADENA
LEFT JOIN [mkt].[maestro_OFICINA] C
ON A.COD_OFI=C.COD_OFICINA
LEFT JOIN [mkt].[maestro_grupotarget] D
ON A.TRAT_COMERCIAL=D.COD_GRUPOTARGET
LEFT JOIN [mkt].[maestro_vendedor] F
ON A.COD_VEND=F.COD_VENDEDOR
LEFT JOIN [mkt].[maestro_tiempo] T
ON A.VBRK_FKDAT=T.Fecha
LEFT JOIN mkt.maestro_fuente_producto G
ON G.[GrpID]='307' AND A.VBRP_MATNR=G.PROIDCLIE
LEFT JOIN [mkt].[maestro_presentacion_producto] PP
ON G.PROPSTID=PP.PROPSTID
LEFT JOIN [mkt].[maestro_precio] H
ON H.GrpID='307' AND H.AÒOSEMANA_GL=T.AÒoSemana_GL AND H.ProPstID=G.PROPSTID
LEFT JOIN [MKT].maestro_pdv PD
ON CONVERT(VARCHAR,CONVERT(INTEGER,VBRK_KUNAG))=PD.COD_PDV


SELECT COUNT(1)  FROM MKT.PRUEBA_QS;--264884

SELECT * FROM  MKT.PRUEBA_QS
WHERE propstid IS NULL 


SELECT PROPSTID,AÒoSemana_GL,COUNT(1)  FROM  MKT.PRUEBA_QS
WHERE PRECIOID IS NULL 
GROUP BY PROPSTID,AÒoSemana_GL


SELECT A.*,K.ProPstNombre FROM 
(
SELECT PROPSTID,COUNT(1) TOTAL,MIN(AÒoSemana_GL) MIN_AS,MAX(AÒoSemana_GL) MAX_AS  FROM  MKT.PRUEBA_QS
WHERE PRECIOID IS NULL 
GROUP BY PROPSTID
) A
LEFT JOIN MKT.MAESTRO_PRESENTACION_PRODUCTO K
ON A.PROPSTID=K.PROPSTID


insert into [mkt].[maestro_precio]
SELECT 
NEXT VALUE FOR mkt.PRECIOID OVER(ORDER BY [GrpID],[ProPstID],AÒoSemana_GL),
A.*
FROM 
(
SELECT 
'307' GRPID,PROPSTID,AÒoSemana_GL,0 PRECIO FROM  MKT.PRUEBA_QS
WHERE PRECIOID IS NULL 
GROUP BY PROPSTID,AÒoSemana_GL
) A

SELECT DISTINCT CONVERT(VARCHAR,CONVERT(INTEGER,VBRK_KUNAG)) FROM MKT.PRUEBA_QS
WHERE PDVID IS NULL 
/*VALIDACIONES*/

/*CHECK PDV*/

insert into [mkt].maestro_pdv
SELECT 
NEXT VALUE FOR mkt.PDVid OVER(ORDER BY VBRK_KUNAG),
	VBRK_KUNAG,
	VBRK_KUNAG,
	VBRK_KUNAG,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL
FROM 
(
SELECT DISTINCT CONVERT(VARCHAR,CONVERT(INTEGER,VBRK_KUNAG)) VBRK_KUNAG  FROM MKT.SO_QS_SUM A
LEFT JOIN [MKT].maestro_pdv PD
ON CONVERT(VARCHAR,CONVERT(INTEGER,VBRK_KUNAG))=PD.COD_PDV
WHERE PDVID IS NULL 
) A

/*CHECK CADENAID*/

insert into [mkt].[maestro_cadena]
SELECT 
NEXT VALUE FOR mkt.cadenaid OVER(ORDER BY [COD_CENTRO]),
[COD_CENTRO],
[COD_CENTRO]
FROM 
(
SELECT DISTINCT COD_CENTRO FROM MKT.SO_QS_SUM a
LEFT JOIN [mkt].[maestro_cadena] B
ON A.COD_CENTRO=B.COD_CADENA
WHERE B.CADENAID IS NULL 
) A

/*CHECK OFICINAID*/

insert into [mkt].[maestro_oficina]
SELECT 
NEXT VALUE FOR mkt.oficinaid OVER(ORDER BY COD_OFI),
COD_OFI,
COD_OFI
FROM 
(
SELECT DISTINCT COD_OFI FROM MKT.SO_QS_SUM a
LEFT JOIN [mkt].[maestro_oficina] B
ON A.COD_OFI=B.COD_OFICINA
WHERE B.OFICINAID IS NULL 
) A

/*CHECK TARGETGROUP*/

insert into [mkt].[maestro_grupotarget]
SELECT 
NEXT VALUE FOR mkt.grupotargetid OVER(ORDER BY TRAT_COMERCIAL),
TRAT_COMERCIAL,
TRAT_COMERCIAL
FROM 
(
SELECT DISTINCT TRAT_COMERCIAL FROM MKT.SO_QS_SUM a
LEFT JOIN [mkt].[maestro_grupotarget] B
ON A.TRAT_COMERCIAL=B.COD_GRUPOTARGET
WHERE B.GRUPOTARGETID IS NULL 
) A

/*CHECK VENDEDOR*/

insert into [mkt].[maestro_vendedor]
SELECT 
NEXT VALUE FOR mkt.vendedorid OVER(ORDER BY COD_VEND),
COD_VEND,
COD_VEND
FROM 
(
SELECT DISTINCT COD_VEND FROM MKT.SO_QS_SUM a
LEFT JOIN [mkt].[maestro_vendedor] B
ON A.COD_VEND=B.COD_VENDEDOR
WHERE B.VENDEDORID IS NULL 
) A

/*CHECK PRESENTACION PRODUCTO*/

--SELECT * FROM mkt.maestro_fuente_producto

insert into mkt.maestro_fuente_producto
SELECT 
VBRP_MATNR,
'307' GRPID,
'0000' PROPSTID
FROM
(
SELECT DISTINCT VBRP_MATNR FROM MKT.SO_QS_SUM a
LEFT JOIN [mkt].maestro_fuente_producto B
ON A.VBRP_MATNR=B.PROIDCLIE AND B.GrpID='307'
WHERE B.PROPSTID IS NULL 
) A

/*CHECK PRECIO*/

insert into [mkt].[maestro_precio]
SELECT 
NEXT VALUE FOR mkt.PRECIOID OVER(ORDER BY [GrpID],[ProPstID],AÒoSemana_GL),
A.*
FROM 
(
SELECT 
'307' GRPID,PROPSTID,AÒoSemana_GL,0 PRECIO FROM
(
SELECT Q.PROPSTID,Q.AÒoSemana_GL FROM
(
SELECT DISTINCT B.PROPSTID,T.AÒoSemana_GL FROM
MKT.SO_QS_SUM A
LEFT JOIN MKT.maestro_fuente_producto B
ON A.VBRP_MATNR=B.PROIDCLIE
LEFT JOIN MKT.maestro_tiempo T
ON A.VBRK_FKDAT=T.Fecha
) Q LEFT JOIN mkt.maestro_precio H
ON H.GrpID='307' AND H.AÒOSEMANA_GL=Q.AÒoSemana_GL AND H.ProPstID=Q.PROPSTID
WHERE H.PRECIO_LISTA IS NULL 
) P
) A

/************/
SELECT CONVERT(VARCHAR,S.AÒO*100+S.SEMANA) AÒOSEMANA,CD_CENTRO,CODIGO_SAP,SUM(CANT_01) CANT_01,SUM(CANT_02) CANT_02
INTO [mkt].[STOCK_QS_HISTW_SEM]
FROM [mkt].[STOCK_QS_HISTW] S
GROUP BY CONVERT(VARCHAR,S.AÒO*100+S.SEMANA),CD_CENTRO,CODIGO_SAP
ORDER BY 1,2,3

SELECT * FROM  [mkt].[STOCK_QS_HISTW_SEM]

/*****************/






DROP TABLE MKT.PRUEBA_QS;

SELECT 
A.VBRK_FKDAT FECHA,
B.CADENAID,
B.DESC_CADENA,
A.COD_CENTRO,
C.OFICINAID,
C.DESC_OFICINA,
D.GRUPOTARGETID,
D.DESC_GRUPOTARGET,
F.VENDEDORID,
F.DESC_VENDEDOR,
PP.ProPstID,
PP.ProPstNombre,
PD.PDVID,
PD.PDVNOMBRE,
A.VBRK_KUNAG,
A.CANTIDAD UNIDDESP,
COALESCE(S.CANT_01,0) UNIDCEDIS,
COALESCE(S.CANT_02,0) UNIDTRANS,
A.MONTO MONTODESPCLIENTE,
A.CANTIDAD*H.PRECIO_LISTA MONTODESP,
COALESCE(S.CANT_01,0)*H.PRECIO_LISTA MONTOCEDIS,
COALESCE(S.CANT_02,0)*H.PRECIO_LISTA MONTOTRANS,
H.PRECIOID,
T.AÒoSemana_GL,
A.VBRP_MATNR
INTO MKT.PRUEBA_QS
FROM MKT.SO_QS_SUM A
LEFT JOIN [mkt].[maestro_cadena] B
ON A.COD_CENTRO=B.COD_CADENA
LEFT JOIN [mkt].[maestro_OFICINA] C
ON A.COD_OFI=C.COD_OFICINA
LEFT JOIN [mkt].[maestro_grupotarget] D
ON A.TRAT_COMERCIAL=D.COD_GRUPOTARGET
LEFT JOIN [mkt].[maestro_vendedor] F
ON A.COD_VEND=F.COD_VENDEDOR
LEFT JOIN [mkt].[maestro_tiempo] T
ON A.VBRK_FKDAT=T.Fecha
LEFT JOIN mkt.maestro_fuente_producto G
ON G.[GrpID]='307' AND A.VBRP_MATNR=G.PROIDCLIE
LEFT JOIN [mkt].[maestro_presentacion_producto] PP
ON G.PROPSTID=PP.PROPSTID
LEFT JOIN [mkt].[maestro_precio] H
ON H.GrpID='307' AND H.AÒOSEMANA_GL=T.AÒoSemana_GL AND H.ProPstID=G.PROPSTID
LEFT JOIN [MKT].maestro_pdv PD
ON CONVERT(VARCHAR,CONVERT(INTEGER,VBRK_KUNAG))=PD.COD_PDV
LEFT JOIN [mkt].[STOCK_QS_HISTW_SEM] S
ON S.AÒOSEMANA=T.AÒoSemana_GL AND A.COD_CENTRO=S.CD_CENTRO AND A.VBRP_MATNR=S.CODIGO_SAP

SELECT * FROM 
MKT.PRUEBA_QS


/* TABLA FINAL */

DROP TABLE MKT.SO_QS_FINAL;

SELECT 
A.VBRK_FKDAT FECHA,
B.CADENAID,
C.OFICINAID,
D.GRUPOTARGETID,
F.VENDEDORID,
PP.ProPstID,
PD.PDVID,
H.PRECIOID,
A.CANTIDAD UNIDDESP,
COALESCE(S.CANT_01,0) UNIDCEDIS,
COALESCE(S.CANT_02,0) UNIDTRANS,
A.MONTO MONTODESPCLIENTE,
A.CANTIDAD*H.PRECIO_LISTA MONTODESP,
COALESCE(S.CANT_01,0)*H.PRECIO_LISTA MONTOCEDIS,
COALESCE(S.CANT_02,0)*H.PRECIO_LISTA MONTOTRANS,
T.AÒoSemana_GL
INTO MKT.SO_QS_FINAL
FROM MKT.SO_QS_SUM A
LEFT JOIN [mkt].[maestro_cadena] B
ON A.COD_CENTRO=B.COD_CADENA
LEFT JOIN [mkt].[maestro_OFICINA] C
ON A.COD_OFI=C.COD_OFICINA
LEFT JOIN [mkt].[maestro_grupotarget] D
ON A.TRAT_COMERCIAL=D.COD_GRUPOTARGET
LEFT JOIN [mkt].[maestro_vendedor] F
ON A.COD_VEND=F.COD_VENDEDOR
LEFT JOIN [mkt].[maestro_tiempo] T
ON A.VBRK_FKDAT=T.Fecha
LEFT JOIN mkt.maestro_fuente_producto G
ON G.[GrpID]='307' AND A.VBRP_MATNR=G.PROIDCLIE
LEFT JOIN [mkt].[maestro_presentacion_producto] PP
ON G.PROPSTID=PP.PROPSTID
LEFT JOIN [mkt].[maestro_precio] H
ON H.GrpID='307' AND H.AÒOSEMANA_GL=T.AÒoSemana_GL AND H.ProPstID=G.PROPSTID
LEFT JOIN [MKT].maestro_pdv PD
ON CONVERT(VARCHAR,CONVERT(INTEGER,VBRK_KUNAG))=PD.COD_PDV
LEFT JOIN [mkt].[STOCK_QS_HISTW_SEM] S
ON S.AÒOSEMANA=T.AÒoSemana_GL AND A.COD_CENTRO=S.CD_CENTRO AND A.VBRP_MATNR=S.CODIGO_SAP



SELECT * FROM MKT.SO_QS_FINAL
WHERE ProPstID IS NULL 


SELECT * FROM mkt.maestro_fuente_producto
WHERE propstid IS NULL 






DROP TABLE PER.STOCK_QS;

SELECT 
B.ProPstID,
C.CadenaID,
SUM(A.CANT_01) UnidCedis,
SUM(A.CANT_02) UnidTrans,
D.Fecha
into PER.STOCK_QS
FROM 
(
SELECT * FROM 
mkt.STOCK_QS_HISTW 
WHERE CODIGO_SAP<>'116854'
)
a
LEFT JOIN per.MAESTRO_PRODUCTO_FUENTE B
ON A.CODIGO_SAP=B.ProIDClie AND B.GrpID='307'
LEFT JOIN per.MAESTRO_CADENA C
ON A.CD_CENTRO=C.CadenaIDClie
LEFT JOIN per.MAESTRO_TIEMPO D
ON D.Fecha=A.FECHA
GROUP BY B.ProPstID,
C.CadenaID,D.Fecha

SELECT MIN(FECHA),MAX(FECHA) FROM PER.STOCK_QS