/*
DELETE FROM MKT.SELLOUT_QS_HIST
WHERE SUBSTRING(VBRK_FKDAT,1,6)=SUBSTRING('20150531',1,6);

insert into MKT.SELLOUT_QS_HIST
SELECT * FROM mkt.sellout_qs_day;
*/
DELETE FROM  mkt.so_qs_3;
DELETE FROM  mkt.so_qs_2;
DELETE FROM  mkt.so_qs_1;

insert into mkt.so_qs_1
SELECT [ID]
      ,[FECHAGEN]
      ,[VBRP_MATKL]
      ,[VBRP_MATNR]
      ,[WPROD]
      ,[VBRK_KUNAG]
      ,[KNA1_STCD1]
      ,[UBIGEO]
      ,[COD_VEND]
      ,[COD_PROM]
      ,[FREE1]
      ,[COD_OFI]
      ,[COD_CENTRO]
      ,[COD_ALM]
      ,[VBAK_VBELN]
      ,[VBKD_BSARK_E]
      ,[VBRK_VBELN]
      ,[VBRP_POSNR]
      ,[VBRK_XBLNR]
      ,[VBRK_ERDAT]
      ,[VBRK_FKART]
      ,[VBRK_FKDAT]
      ,[VBRK_ZZRFOFI]
      ,[VBRP_CHARG]
      ,[VBRK_ZTERM]
      ,[VBRP_AUGRU_AUFT]
      ,[VBRK_FKSTO]
	  ,CASE WHEN len([VBRP_FKIMG])=12 THEN CAST(SUBSTRING([VBRP_FKIMG],2,11) AS DECIMAL(12,3))/-1000 ELSE CAST([VBRP_FKIMG] AS DECIMAL(12,3))/1000 END [VBRP_FKIMG]
      ,[VBRP_VRKME]
	  ,CAST([VBRP_ZZ_ZP01] AS DECIMAL(12,2))/100 [VBRP_ZZ_ZP01]
      ,[VBRK_WAERK]
      ,CAST([DESC_RR] AS DECIMAL(7,2))/100 [DESC_RR]
	  ,CAST([DESC_NR] AS DECIMAL(7,2))/100 [DESC_NR]
      ,CASE WHEN len([VBRP_KZWI1])=12 THEN CAST(SUBSTRING([VBRP_KZWI1],2,11) AS DECIMAL(12,2))/-100 ELSE CAST([VBRP_KZWI1] AS DECIMAL(12,2))/100 END [VBRP_KZWI1]
	  ,CASE WHEN len([ZVALVTA_UNI])=12 THEN CAST(SUBSTRING([ZVALVTA_UNI],2,11) AS DECIMAL(12,2))/-100 ELSE CAST([ZVALVTA_UNI] AS DECIMAL(12,2))/100 END [ZVALVTA_UNI]
	  ,CASE WHEN len([ZIMP_BRUTO])=12 THEN CAST(SUBSTRING([ZIMP_BRUTO],2,11) AS DECIMAL(12,2))/-100 ELSE CAST([ZIMP_BRUTO] AS DECIMAL(12,2))/100 END [ZIMP_BRUTO]
      ,CAST([ZMARGEN] AS DECIMAL(6,2))/100 [ZMARGEN]
	  ,CASE WHEN len([ZVAL_VTAIMP])=12 THEN CAST(SUBSTRING([ZVAL_VTAIMP],2,11) AS DECIMAL(12,2))/-100 ELSE CAST([ZVAL_VTAIMP] AS DECIMAL(12,2))/100 END [ZVAL_VTAIMP]
      ,CASE WHEN len([ZIMP_IMPTO])=12 THEN CAST(SUBSTRING([ZIMP_IMPTO],2,11) AS DECIMAL(12,2))/-100 ELSE CAST([ZIMP_IMPTO] AS DECIMAL(12,2))/100 END [ZIMP_IMPTO]
      ,CAST([DESC_QS] AS DECIMAL(6,2))/100 [DESC_QS]
      ,CASE WHEN len([ZVALNETO])=12 THEN CAST(SUBSTRING([ZVALNETO],2,11) AS DECIMAL(12,2))/-100 ELSE CAST([ZVALNETO] AS DECIMAL(12,2))/100 END [ZVALNETO]
      ,[CLS_PED]
      ,[IND_BONIF]
	  ,CASE WHEN len([ZVALNET_CFLETE])=12 THEN CAST(SUBSTRING([ZVALNET_CFLETE],2,11) AS DECIMAL(12,2))/-100 ELSE CAST([ZVALNET_CFLETE] AS DECIMAL(12,2))/100 END [ZVALNET_CFLETE]
	  ,CASE WHEN len([VAL_DESC_RR])=12 THEN CAST(SUBSTRING([VAL_DESC_RR],2,11) AS DECIMAL(12,2))/-100 ELSE CAST([VAL_DESC_RR] AS DECIMAL(12,2))/100 END [VAL_DESC_RR]
      ,CASE WHEN len([VAL_DESC_NR])=12 THEN CAST(SUBSTRING([VAL_DESC_NR],2,11) AS DECIMAL(12,2))/-100 ELSE CAST([VAL_DESC_NR] AS DECIMAL(12,2))/100 END [VAL_DESC_NR]
	  ,CASE WHEN len([VAL_DESC_QS])=12 THEN CAST(SUBSTRING([VAL_DESC_QS],2,11) AS DECIMAL(12,2))/-100 ELSE CAST([VAL_DESC_QS] AS DECIMAL(12,2))/100 END [VAL_DESC_QS]
	  ,CASE WHEN len([VAL_FLETE_APROV])=12 THEN CAST(SUBSTRING([VAL_FLETE_APROV],2,11) AS DECIMAL(12,2))/-100 ELSE CAST([VAL_FLETE_APROV] AS DECIMAL(12,2))/100 END [VAL_FLETE_APROV]
      ,CASE WHEN len([ZVALNETO_SF_QS])=12 THEN CAST(SUBSTRING([ZVALNETO_SF_QS],2,11) AS DECIMAL(12,2))/-100 ELSE CAST([ZVALNETO_SF_QS] AS DECIMAL(12,2))/100 END [ZVALNETO_SF_QS]
      ,CAST([TIPO_CAMBIO] AS DECIMAL(12,5))/100000 [TIPO_CAMBIO]
      ,CAST([PJE_DSCTO_CE] AS DECIMAL(5,2))/100 [PJE_DSCTO_CE]
	  ,CASE WHEN len([VALOR_DSCTO_CE])=12 THEN CAST(SUBSTRING([VALOR_DSCTO_CE],2,11) AS DECIMAL(12,2))/-100 ELSE CAST([VALOR_DSCTO_CE] AS DECIMAL(12,2))/100 END [VALOR_DSCTO_CE]
      ,CASE WHEN len([COSTO_UNIT])=12 THEN CAST(SUBSTRING([COSTO_UNIT],2,11) AS DECIMAL(12,2))/-100 ELSE CAST([COSTO_UNIT] AS DECIMAL(12,2))/100 END [COSTO_UNIT]
      ,[ORG_VTAS]
      ,[SECTOR]
      ,[CARACT_NEG]
      ,[TRAT_COMERCIAL]
  FROM mkt.sellout_qs_day;

DELETE FROM MKT.SELLOUT_QS_HISTW
WHERE VBRK_FKDAT in
(SELECT DISTINCT VBRK_FKDAT FROM mkt.so_qs_1)

insert into [mkt].[SELLOUT_QS_HISTW]
SELECT * FROM mkt.so_qs_1;

insert INTO mkt.so_qs_2
SELECT 
VBRK_FKDAT	,
COD_CENTRO	,
COD_OFI	,
TRAT_COMERCIAL	,
VBRK_KUNAG	,
COD_VEND	,
VBRP_MATNR,
SUM(VBRP_FKIMG) CANTIDAD,
SUM(ZVALNETO_SF_QS) MONTO
FROM 
(
SELECT * FROM 
mkt.so_qs_1
WHERE 
VBRP_MATNR NOT IN ('186271','116854')
) a
GROUP BY 
VBRK_FKDAT	,
COD_CENTRO	,
COD_OFI	,
TRAT_COMERCIAL	,
VBRK_KUNAG	,
COD_VEND	,
VBRP_MATNR;

/*CHECK PRESENTACION PRODUCTO*/

--SELECT * FROM per.maestro_fuente_producto

insert into per.MAESTRO_PRODUCTO_FUENTE
SELECT 
VBRP_MATNR,
'307' GRPID,
'0000' PROPSTID
FROM
(
SELECT DISTINCT VBRP_MATNR FROM mkt.so_qs_2 a
LEFT JOIN [per].MAESTRO_PRODUCTO_FUENTE B
ON A.VBRP_MATNR=B.PROIDCLIE AND B.GrpID='307'
WHERE B.PROPSTID IS NULL 
) A;

/*CHECK PDV*/
print ('validaciones')
insert into [per].maestro_pdv
SELECT 
NEXT VALUE FOR per.seq_PDVid OVER(ORDER BY VBRK_KUNAG),
	VBRK_KUNAG,
	VBRK_KUNAG,
	VBRK_KUNAG,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	'307'
FROM 
(
SELECT DISTINCT CONVERT(VARCHAR,CONVERT(INTEGER,VBRK_KUNAG)) VBRK_KUNAG  FROM MKT.so_qs_2 A
LEFT JOIN [per].maestro_pdv PD
ON CONVERT(VARCHAR,CONVERT(INTEGER,VBRK_KUNAG))=PD.PdvIDClie AND PD.GrpID='307'
WHERE PDVID IS NULL 
) A;

/*CHECK CADENAID*/

insert into [per].[maestro_cadena]
SELECT 
NEXT VALUE FOR per.seq_cadenaid OVER(ORDER BY [COD_CENTRO]),
[COD_CENTRO],
[COD_CENTRO],
'307'
FROM 
(
SELECT DISTINCT COD_CENTRO FROM MKT.so_qs_2 a
LEFT JOIN [per].[maestro_cadena] B
ON A.COD_CENTRO=B.CadenaIDClie
WHERE B.CADENAID IS NULL 
) A;

/*CHECK OFICINAID*/

insert into [per].[maestro_oficina]
SELECT 
NEXT VALUE FOR per.seq_oficinaid OVER(ORDER BY COD_OFI),
COD_OFI,
COD_OFI,
'307'
FROM 
(
SELECT DISTINCT COD_OFI FROM mkt.so_qs_2 a
LEFT JOIN [per].[maestro_oficina] B
ON A.COD_OFI=B.OficinaIDClie
WHERE B.OFICINAID IS NULL 
) A;


/*CHECK TARGETGROUP*/

insert into [per].MAESTRO_GRUPO1
SELECT 
NEXT VALUE FOR [per].[seq_Grupo1id] OVER(ORDER BY TRAT_COMERCIAL),
TRAT_COMERCIAL,
TRAT_COMERCIAL,
'307'
FROM 
(
SELECT DISTINCT TRAT_COMERCIAL FROM mkt.so_qs_2 a
LEFT JOIN [per].MAESTRO_GRUPO1 B
ON A.TRAT_COMERCIAL=B.Grupo1IDClie
WHERE B.Grupo1ID IS NULL 
) A;

/*CHECK VENDEDOR*/

insert into [per].[maestro_vendedor]
SELECT 
NEXT VALUE FOR [per].[seq_vendedorid] OVER(ORDER BY COD_VEND),
COD_VEND,
COD_VEND,
'307'
FROM 
(
SELECT DISTINCT COD_VEND FROM mkt.so_qs_2 a
LEFT JOIN [per].[maestro_vendedor] B
ON A.COD_VEND=B.VendedorIDClie
WHERE B.VENDEDORID IS NULL 
) A;

/*CHECK PRECIO*/

insert into [per].MAESTRO_PRODUCTO_PRECIO
SELECT 
NEXT VALUE FOR [per].[seq_precioid] OVER(ORDER BY [GrpID],[ProPstID],AÒoSemana_GL),
A.*
FROM 
(
SELECT 
'307' GRPID,PROPSTID,AÒoSemana_GL,0 PRECIO FROM
(
SELECT Q.PROPSTID,Q.AÒoSemana_GL FROM
(
SELECT DISTINCT B.PROPSTID,T.AÒoSemana_GL FROM
mkt.so_qs_2 A
LEFT JOIN per.MAESTRO_PRODUCTO_FUENTE B
ON A.VBRP_MATNR=B.PROIDCLIE
LEFT JOIN per.MAESTRO_TIEMPO T
ON A.VBRK_FKDAT=T.Fecha
) Q LEFT JOIN per.MAESTRO_PRODUCTO_PRECIO H
ON H.GrpID='307' AND H.AÒOSEMANA_GL=Q.AÒoSemana_GL AND H.ProPstID=Q.PROPSTID
WHERE H.PrecioLista IS NULL 
) P
) A;

print('ingreso a tabla final')

insert INTO mkt.so_qs_3
SELECT 
A.VBRK_FKDAT Fecha,
'307' GrpID,
B.CadenaID,
C.OficinaID,
D.Grupo1ID GrupoTratID,
F.VendedorID,
S.SupervisorID,
PP.ProPstID,
PD.PdvID,
H.PrecioID,
A.CANTIDAD UnidDesp,
A.MONTO MontoDespCliente,
A.CANTIDAD*H.PrecioLista MontoDesp,
T.AÒoSemana_GL
FROM mkt.so_qs_2 A
LEFT JOIN per.[maestro_cadena] B
ON A.COD_CENTRO=B.CadenaIDClie AND B.GrpID='307'
LEFT JOIN per.[maestro_OFICINA] C
ON A.COD_OFI=C.OficinaIDClie AND C.GrpID='307'
LEFT JOIN per.[MAESTRO_GRUPO1] D
ON A.TRAT_COMERCIAL=D.Grupo1IDClie AND D.GrpID='307'
LEFT JOIN per.[maestro_vendedor] F
ON A.COD_VEND=F.VendedorIDClie AND F.GrpID='307'
LEFT JOIN per.[maestro_supervisor] S
ON NULL=S.SupervisorIDClie AND S.GrpID='307'
LEFT JOIN per.[maestro_tiempo] T
ON A.VBRK_FKDAT=T.Fecha
LEFT JOIN per.maestro_producto_fuente G
ON A.VBRP_MATNR=G.PROIDCLIE AND G.[GrpID]='307'
LEFT JOIN per.[maestro_producto_presentacion] PP
ON G.PROPSTID=PP.PROPSTID
LEFT JOIN per.[maestro_producto_precio] H
ON H.AÒOSEMANA_GL=T.AÒoSemana_GL AND H.ProPstID=G.PROPSTID AND H.GrpID='307'
LEFT JOIN per.maestro_pdv PD
ON CONVERT(VARCHAR,CONVERT(INTEGER,VBRK_KUNAG))=PD.PdvIDClie AND PD.GrpID='307';

DELETE FROM [per].[SELLOUT_QS]
WHERE FECHA in
(SELECT DISTINCT Fecha FROM mkt.so_qs_3)

insert into [per].[SELLOUT_QS]
SELECT * FROM mkt.so_qs_3;




