
/*MAESTRO PROMOTOR*/

DROP SEQUENCE  per.seq_promotorid;

CREATE SEQUENCE per.seq_promotorid as int
MINVALUE 100000
NO CYCLE

DROP TABLE [per].MAESTRO_PROMOTOR;
CREATE TABLE [per].MAESTRO_PROMOTOR(
	PromotorID [VARCHAR](6) PRIMARY KEY,
	PromotorIDClie [varchar](7) NULL,
	DescPromotor [varchar](50) NULL,
	GrpID [varchar](3) NOT NULL
) ON [PRIMARY]

ALTER TABLE [per].MAESTRO_PROMOTOR
ADD CONSTRAINT FK_PRO_CLI FOREIGN KEY ([GrpID])
REFERENCES per.MAESTRO_CLIENTE([GrpID]);

SELECT * FROM per.MAESTRO_PROMOTOR