/*MAESTRO PRESENTACION*/

SELECT * FROM MKT.maestro_productox

/*MAESTRO AGRUPACION PAUTA*/
SELECT DISTINCT A.AGRPROID,A.AGRPRONOMBRE FROM MKT.maestro_productox A

CREATE TABLE per.[MAESTRO_PRODUCTO_AGRPAUTA](
	AgrProID [VARCHAR](4) PRIMARY KEY,
	AgrProNombre [varchar](50) NULL,
) ON [PRIMARY]

insert into per.[MAESTRO_PRODUCTO_AGRPAUTA]
SELECT DISTINCT A.AGRPROID,A.AGRPRONOMBRE FROM MKT.maestro_productox A

SELECT * FROM per.[MAESTRO_PRODUCTO_AGRPAUTA]

/*MAESTRO LINEA PRODUCTO*/

SELECT DISTINCT LINID,LINNOMBRE FROM MKT.maestro_productox
DROP TABLE per.[MAESTRO_PRODUCTO_LINEA];
CREATE TABLE per.[MAESTRO_PRODUCTO_LINEA](
	LinID [VARCHAR](3) PRIMARY KEY,
	LinNombre [varchar](30) NULL,
) ON [PRIMARY]

insert into per.[MAESTRO_PRODUCTO_LINEA]
SELECT DISTINCT A.LINID,A.LINNOMBRE FROM MKT.maestro_productox A

SELECT * FROM per.[MAESTRO_PRODUCTO_LINEA]

/*MAESTRO MARCA*/

SELECT DISTINCT MrcID,MrcNombre FROM MKT.maestro_productox

DROP TABLE per.MAESTRO_PRODUCTO_MARCA;
CREATE TABLE per.MAESTRO_PRODUCTO_MARCA(
	MrcID [VARCHAR](3) PRIMARY KEY,
	MrcNombre [varchar](20) NULL,
) ON [PRIMARY]


insert into per.MAESTRO_PRODUCTO_MARCA
SELECT DISTINCT A.MRCID,A.MRCNOMBRE FROM MKT.maestro_productox A

SELECT * FROM per.MAESTRO_PRODUCTO_MARCA

/*MAESTRO PRODUCTO*/

SELECT DISTINCT ProID,ProNombre INTO abc FROM MKT.maestro_productox

DROP TABLE per.[MAESTRO_PRODUCTO];
CREATE TABLE per.[MAESTRO_PRODUCTO](
	ProID [VARCHAR](4) PRIMARY KEY,
	ProNombre [varchar](65) NULL,
) ON [PRIMARY]

insert into per.[MAESTRO_PRODUCTO]
SELECT DISTINCT A.PROID,A.PRONOMBRE FROM MKT.maestro_productox A
WHERE PROID<>'1412'

insert into per.[MAESTRO_PRODUCTO]
SELECT DISTINCT A.PROID,'SILKA ORTHOPEDIC PLANTILLA GEL - PER' FROM MKT.maestro_productox A
WHERE PROID='1412'


/* MAESTRO PRESENTACION*/

DROP TABLE per.[MAESTRO_PRODUCTO_PRESENTACION];
CREATE TABLE per.[MAESTRO_PRODUCTO_PRESENTACION](
	[ProPstID] [varchar](4) PRIMARY KEY,
	[ProPstCodBarras] [varchar](13) NULL,
	[ProPstCodigoAtlas] [varchar](15) NULL,
	[ProPstNombre] [varchar](100) NULL,
	[ProID] [VARCHAR](4) NOT NULL,
	[AgrProID] [VARCHAR](4) NOT NULL,
	[LinID] [VARCHAR](3) NOT NULL,
	[MrcID] [VARCHAR](3) NOT NULL,
) ON [PRIMARY]


ALTER TABLE [per].[MAESTRO_PRODUCTO_PRESENTACION]
ADD CONSTRAINT FK_PRE_PRO FOREIGN KEY (PROID)
REFERENCES [per].[MAESTRO_PRODUCTO](PROID)


ALTER TABLE [per].[MAESTRO_PRODUCTO_PRESENTACION]
ADD CONSTRAINT FK_PRE_AGR FOREIGN KEY ([AgrProID])
REFERENCES [per].[MAESTRO_PRODUCTO_AGRPAUTA]([AgrProID])


ALTER TABLE [per].[MAESTRO_PRODUCTO_PRESENTACION]
ADD CONSTRAINT FK_PRE_MRC FOREIGN KEY (MRCID)
REFERENCES [per].[MAESTRO_PRODUCTO_MARCA](MRCID)

ALTER TABLE [per].[MAESTRO_PRODUCTO_PRESENTACION]
ADD CONSTRAINT FK_PRE_LIN FOREIGN KEY (LINID)
REFERENCES [per].[MAESTRO_PRODUCTO_LINEA](LINID)

INSERT INTO [per].[MAESTRO_PRODUCTO_PRESENTACION]
SELECT
	[ProPstID],
	CONVERT(varchar(12),[ProPstCodBarras]),
	[ProPstCodigoAtlas],
	[ProPstNombre],
	[ProID],
	[AgrProID],
	[LinID],
	[MrcID]
FROM MKT.maestro_productox

SELECT * FROM per.[MAESTRO_PRODUCTO_PRESENTACION]

/* MAESTRO FUENTE PRODUCTO*/

DROP TABLE  per.MAESTRO_PRODUCTO_FUENTE;
CREATE TABLE per.MAESTRO_PRODUCTO_FUENTE(
	ProIDClie [VARCHAR](12) NULL,
	GrpID [varchar](3) NULL,
	ProPstID [varchar](4) NULL
) ON [PRIMARY]

ALTER TABLE per.MAESTRO_PRODUCTO_FUENTE
ADD CONSTRAINT FK_FUE_PRO FOREIGN KEY (PROPSTID)
REFERENCES per.[MAESTRO_PRODUCTO_PRESENTACION](PROPSTID)

ALTER TABLE per.MAESTRO_PRODUCTO_FUENTE
ADD CONSTRAINT FK_FUE_GRP FOREIGN KEY ([GrpID])
REFERENCES per.MAESTRO_CLIENTE([GrpID])


insert into per.MAESTRO_PRODUCTO_FUENTE
SELECT
rtrim(ltrim(ProIDClie)),
rtrim(ltrim(CadID)),
rtrim(ltrim(PROPSTID))
FROM  mkt.maestro_fuente_productox

SELECT LEN(PROPSTID),PROPSTID FROM mkt.maestro_fuente_productox
ORDER BY 1

/*registros eliminados*/
delete FROM [mkt].maestro_fuente_productox
WHERE rtrim(ltrim([ProPstID])) NOT IN
(SELECT [ProPstID] FROM MKT.maestro_presentacion_producto)


SELECT * FROM mkt.maestro_fuente_producto



INSERT INTO [per].[MAESTRO_PRODUCTO_AGRPAUTA]
VALUES('0000','SIN AGRUPACION PAUTA')

INSERT INTO [per].[MAESTRO_PRODUCTO_LINEA]
VALUES('000','SIN LINEA PRODUCTO')

INSERT INTO [per].[MAESTRO_PRODUCTO_MARCA]
VALUES('000','SIN MARCA PRODUCTO')

INSERT INTO [per].[MAESTRO_PRODUCTO]
VALUES('0000','SIN CODIGO PRODUCTO')

INSERT INTO [per].[MAESTRO_PRODUCTO_PRESENTACION]
VALUES('0000','000000000000','0000000000000','SIN PRODUCTO PRESENTACION','0000','0000','000','000')