

/*MAESTRO PRECIO*/
SELECT * FROM [mkt].[maestro_preciox]

DROP TABLE [per].[MAESTRO_PRODUCTO_PRECIO];
CREATE TABLE [per].[MAESTRO_PRODUCTO_PRECIO](
	[PrecioID] VARCHAR(6) PRIMARY KEY,
	[GrpID] VARCHAR(3) NOT NULL,
	[ProPstID] VARCHAR(4) NOT NULL,
	[AÒoSemana_GL] VARCHAR(6) NOT NULL,
	[PrecioLista] DECIMAL(15,4) NULL
) ON [PRIMARY]


ALTER TABLE [per].[MAESTRO_PRODUCTO_PRECIO]
ADD CONSTRAINT FK_PRECIO_CLI FOREIGN KEY ([GrpID])
REFERENCES per.MAESTRO_CLIENTE([GrpID]);

ALTER TABLE [per].[MAESTRO_PRODUCTO_PRECIO]
ADD CONSTRAINT FK_PRECIO_PREPRO FOREIGN KEY ([ProPstID])
REFERENCES per.[MAESTRO_PRODUCTO_PRESENTACION]([ProPstID]);

ALTER TABLE [per].[MAESTRO_PRODUCTO_PRECIO]
ADD CONSTRAINT FK_PRECIO_AS FOREIGN KEY ([AÒOSEMANA_GL])
REFERENCES [per].[maestro_aÒosemana_gl]([AÒOSEMANA_GL]);

DROP SEQUENCE  per.seq_precioid;

CREATE SEQUENCE per.seq_precioid as int
MINVALUE 100000
NO CYCLE


insert into [per].[MAESTRO_PRODUCTO_PRECIO]
SELECT
NEXT VALUE FOR per.seq_precioid OVER(ORDER BY [GrpID],[ProPstID],[AÒOSEMANA]),
a.*
FROM [mkt].[maestro_preciox] a
WHERE PRECIO_LISTA IS NOT NULL

SELECT * FROM [per].[MAESTRO_PRODUCTO_PRECIO]


DELETE FROM [mkt].[maestro_preciox]
WHERE [ProPstID] NOT IN
(SELECT [ProPstID] FROM MKT.maestro_presentacion_producto)

DELETE FROM MKT.[maestro_precio]
WHERE PRECIO_LISTA IS NULL
