
/*MAESTRO SUPERVISOR*/

DROP SEQUENCE  per.seq_supervisorid;

CREATE SEQUENCE per.seq_supervisorid as int
MINVALUE 100000
NO CYCLE

DROP TABLE [per].MAESTRO_SUPERVISOR;
CREATE TABLE [per].MAESTRO_SUPERVISOR(
	SupervisorID [VARCHAR](6) PRIMARY KEY,
	SupervisorIDClie [varchar](5) NULL,
	DescSupervisor [varchar](50) NULL,
	GrpID [varchar](3) NOT NULL
) ON [PRIMARY]

ALTER TABLE [per].MAESTRO_SUPERVISOR
ADD CONSTRAINT FK_SUP_CLI FOREIGN KEY ([GrpID])
REFERENCES per.MAESTRO_CLIENTE([GrpID]);


ALTER TABLE per.MAESTRO_SUPERVISOR ALTER COLUMN SupervisorIDClie VARCHAR(7)
ALTER TABLE per.MAESTRO_SUPERVISOR ALTER COLUMN SupervisorIDClie VARCHAR(8)

SELECT * FROM per.MAESTRO_SUPERVISOR
