
/*FACT TABLES*/

/*SELLOUT_QS*/

ALTER TABLE [per].[SELLOUT_QS] with check
ADD CONSTRAINT FK_SOQS_PRO FOREIGN KEY (PROPSTID)
REFERENCES per.[MAESTRO_PRODUCTO_PRESENTACION](PROPSTID)

ALTER TABLE per.MAESTRO_TIEMPO ALTER COLUMN FECHA VARCHAR(8) NOT NULL;
alter table per.MAESTRO_TIEMPO add primary key (FECHA);

ALTER TABLE [per].[SELLOUT_QS] with check
ADD CONSTRAINT FK_SOQS_TIM FOREIGN KEY (FECHA)
REFERENCES per.[MAESTRO_TIEMPO](FECHA)

ALTER TABLE [per].[SELLOUT_QS] with check
ADD CONSTRAINT FK_SOQS_VEN FOREIGN KEY ([VendedorID])
REFERENCES per.[MAESTRO_VENDEDOR]([VendedorID])

ALTER TABLE [per].[SELLOUT_QS] with check
ADD CONSTRAINT FK_SOQS_cad FOREIGN KEY ([CadenaID])
REFERENCES per.[MAESTRO_CADENA]([CadenaID])

ALTER TABLE [per].[SELLOUT_QS] with check
ADD CONSTRAINT FK_SOQS_OFI FOREIGN KEY ([OficinaID])
REFERENCES per.[MAESTRO_OFICINA]([OficinaID])

ALTER TABLE [per].[SELLOUT_QS] with check
ADD CONSTRAINT FK_SOQS_G1 FOREIGN KEY ([GrupoTratID])
REFERENCES per.[MAESTRO_GRUPO1](Grupo1id)

ALTER TABLE [per].[SELLOUT_QS] with check
ADD CONSTRAINT FK_SOQS_pdv FOREIGN KEY ([PdvID])
REFERENCES per.[MAESTRO_PDV]([PdvID])

ALTER TABLE [per].[SELLOUT_QS] with check
ADD CONSTRAINT FK_SOQS_PRE FOREIGN KEY ([PrecioID])
REFERENCES per.[MAESTRO_PRODUCTO_PRECIO]([PrecioID])

ALTER TABLE [per].[SELLOUT_QS] with check
ADD CONSTRAINT FK_SOQS_GRP FOREIGN KEY ([GrpID])
REFERENCES per.[MAESTRO_CLIENTE]([GrpID])

ALTER TABLE [per].[SELLOUT_QS] with check
ADD CONSTRAINT FK_SOQS_SUP FOREIGN KEY ([SupervisorID])
REFERENCES per.[MAESTRO_SUPERVISOR]([SupervisorID])

/*STOCK_QS*/

ALTER TABLE [per].[STOCK_QS] with check
ADD CONSTRAINT FK_STQS_TIM FOREIGN KEY (FECHA)
REFERENCES per.[MAESTRO_TIEMPO](FECHA)

ALTER TABLE [per].[STOCK_QS] with check
ADD CONSTRAINT FK_STQS_PRO FOREIGN KEY ([ProPstID])
REFERENCES per.[MAESTRO_PRODUCTO_PRESENTACION]([ProPstID])

ALTER TABLE [per].[STOCK_QS] with check
ADD CONSTRAINT FK_STQS_CAD FOREIGN KEY ([CadenaID])
REFERENCES per.[MAESTRO_CADENA]([CadenaID])

ALTER TABLE [per].[STOCK_QS] with check
ADD CONSTRAINT FK_STQS_PRE FOREIGN KEY ([PrecioID])
REFERENCES per.[MAESTRO_PRODUCTO_PRECIO]([PrecioID])

ALTER TABLE [per].[STOCK_QS] with check
ADD CONSTRAINT FK_STQS_GRP FOREIGN KEY ([GrpID])
REFERENCES per.[MAESTRO_CLIENTE]([GrpID])

ALTER TABLE [per].[STOCK_QS] with check
ADD CONSTRAINT FK_STQS_PDV FOREIGN KEY ([PdvID])
REFERENCES per.[MAESTRO_PDV]([PdvID])