SELECT * FROM per.MAESTRO_PRODUCTO_PRESENTACION

SELECT
  A.ProPstID,B.ProPstID
FROM [dbo].[Producto$] A
LEFT JOIN PER.MAESTRO_PRODUCTO_PRESENTACION B
  ON A.ProPstID=B.ProPstID

SELECT DISTINCT LEN(StatusLanzamiento),StatusLanzamiento FROM [dbo].[Producto$]


ALTER TABLE genomma.per.MAESTRO_PRODUCTO_PRESENTACION ADD SegmentacionGL VARCHAR(12)  NULL;
ALTER TABLE genomma.per.MAESTRO_PRODUCTO_PRESENTACION ADD Rubro VARCHAR(12)  NULL;
ALTER TABLE genomma.per.MAESTRO_PRODUCTO_PRESENTACION ADD StatusProd VARCHAR(15)  NULL;
ALTER TABLE genomma.per.MAESTRO_PRODUCTO_PRESENTACION ADD StatusLanzamiento VARCHAR(20)  NULL;


UPDATE A
SET A.SegmentacionGL=b.[Segmentación GL],A.Rubro=B.Rubro,A.StatusProd=B.StatusProd,A.StatusLanzamiento=B.StatusLanzamiento,
  A.ProPstCodBarras=CONVERT(VARCHAR,CONVERT(BIGINT,B.ProPstCodBarras)),A.ProPstCodigoAtlas=B.ProPstCodigoAtlas
    FROM PER.MAESTRO_PRODUCTO_PRESENTACION A
    INNER JOIN DBO.[Producto$] B
ON A.ProPstID=B.ProPstID;


SELECT * FROM PER.MAESTRO_PRODUCTO_PRESENTACION







