SELECT SUBSTRING(A.FECHA,1,6) PERIODO ,A.ProIDClie,B.PROPSTID,C.PROPSTNOMBRE,SUM(A.MONTODESPCLIENTE) FROM
		(
		SELECT * FROM per.GLP_SELLOUT
		WHERE grpid='309' AND FECHA>='20150601'
		) A
	LEFT JOIN per.MAESTRO_PRODUCTO_FUENTE B
	on A.ProIDClie=B.ProIDClie
LEFT JOIN per.MAESTRO_PRODUCTO_PRESENTACION C
			ON B.PROPSTID=C.PROPSTID
GROUP BY SUBSTRING(A.FECHA,1,6),A.ProIDClie,B.PROPSTID,C.PROPSTNOMBRE