SELECT * FROM mkt.SELLOUT_CENCO_HIST_2014

SELECT
  substring(PERIODO,1,4)+substring(PERIODO,6,2)+substring(PERIODO,9,2) FECHA,
  COD_CENCOSUD,
  COD_PRODUCTO_PROVEEDOR,
  DESCRIPCION,
  MARCA,
  ESTADO_PROD,
  UMB,
  COD_LOCAL,
  COD_LOCAL_PROVEEDOR,
  DESCRIPCION_LOCAL,
  ESTADO_LOCAL,
  FORMATO,
  TIPO,
  VTA_PERIODO,
  VTA_PUBLICO,
  VTA_COSTO,
  ARCHIVO
INTO mkt.SELLOUT_CENCO_HISTW
FROM mkt.SELLOUT_CENCO_HIST_2015

INSERT INTO mkt.SELLOUT_CENCO_HISTW
SELECT
  substring(PERIODO,1,4)+substring(PERIODO,6,2)+substring(PERIODO,9,2) FECHA,
  CONVERT(VARCHAR,CONVERT(DECIMAL(15,0),REPLACE(RTRIM(LTRIM(COD_CENCOSUD)),',','.'))) COD_CENCOSUD ,
  COD_PRODUCTO_PROVEEDOR,
  DESCRIPCION,
  MARCA,
  ESTADO_PROD,
  UMB,
  COD_LOCAL,
  COD_LOCAL_PROVEEDOR,
  DESCRIPCION_LOCAL,
  ESTADO_LOCAL,
  FORMATO,
  TIPO,
  CONVERT(DECIMAL(15,6),REPLACE(RTRIM(LTRIM(VTA_PERIODO)),',','.')) VTA_PERIODO,
  CONVERT(DECIMAL(15,6),REPLACE(RTRIM(LTRIM(VTA_PUBLICO)),',','.')) VTA_PUBLICO,
  CONVERT(DECIMAL(15,6),REPLACE(RTRIM(LTRIM(VTA_COSTO)),',','.')) VTA_COSTO,
  ARCHIVO
--INTO mkt.SELLOUT_CENCO_HISTW
FROM mkt.SELLOUT_CENCO_HIST_2014