DROP TABLE mkt.SELLOUT_QZ_HISTW;
SELECT [ID]
      ,[FECHAGEN]
      ,[VBRP_MATKL]
      ,[VBRP_MATNR]
      ,[WPROD]
      ,[VBRK_KUNAG]
      ,[KNA1_STCD1]
      ,[UBIGEO]
      ,[COD_VEND]
      ,[COD_PROM]
      ,[FREE1]
      ,[COD_OFI]
      ,[COD_CENTRO]
      ,[COD_ALM]
      ,[VBAK_VBELN]
      ,[VBKD_BSARK_E]
      ,[VBRK_VBELN]
      ,[VBRP_POSNR]
      ,[VBRK_XBLNR]
      ,[VBRK_ERDAT]
      ,[VBRK_FKART]
      ,[VBRK_FKDAT]
      ,[VBRK_ZZRFOFI]
      ,[VBRP_CHARG]
      ,[VBRK_ZTERM]
      ,[VBRP_AUGRU_AUFT]
      ,[VBRK_FKSTO]
	  ,CASE WHEN len([VBRP_FKIMG])=12 THEN CAST(SUBSTRING([VBRP_FKIMG],2,11) AS DECIMAL(12,3))/-1000 ELSE CAST([VBRP_FKIMG] AS DECIMAL(12,3))/1000 END [VBRP_FKIMG]
      ,[VBRP_VRKME]
	  ,CAST([VBRP_ZZ_ZP01] AS DECIMAL(12,2))/100 [VBRP_ZZ_ZP01]
      ,[VBRK_WAERK]
      ,CAST([DESC_RR] AS DECIMAL(7,2))/100 [DESC_RR]
	  ,CAST([DESC_NR] AS DECIMAL(7,2))/100 [DESC_NR]
      ,CASE WHEN len([VBRP_KZWI1])=12 THEN CAST(SUBSTRING([VBRP_KZWI1],2,11) AS DECIMAL(12,2))/-100 ELSE CAST([VBRP_KZWI1] AS DECIMAL(12,2))/100 END [VBRP_KZWI1]
	  ,CASE WHEN len([ZVALVTA_UNI])=12 THEN CAST(SUBSTRING([ZVALVTA_UNI],2,11) AS DECIMAL(12,2))/-100 ELSE CAST([ZVALVTA_UNI] AS DECIMAL(12,2))/100 END [ZVALVTA_UNI]
	  ,CASE WHEN len([ZIMP_BRUTO])=12 THEN CAST(SUBSTRING([ZIMP_BRUTO],2,11) AS DECIMAL(12,2))/-100 ELSE CAST([ZIMP_BRUTO] AS DECIMAL(12,2))/100 END [ZIMP_BRUTO]
      ,CAST([ZMARGEN] AS DECIMAL(6,2))/100 [ZMARGEN]
	  ,CASE WHEN len([ZVAL_VTAIMP])=12 THEN CAST(SUBSTRING([ZVAL_VTAIMP],2,11) AS DECIMAL(12,2))/-100 ELSE CAST([ZVAL_VTAIMP] AS DECIMAL(12,2))/100 END [ZVAL_VTAIMP]
      ,CASE WHEN len([ZIMP_IMPTO])=12 THEN CAST(SUBSTRING([ZIMP_IMPTO],2,11) AS DECIMAL(12,2))/-100 ELSE CAST([ZIMP_IMPTO] AS DECIMAL(12,2))/100 END [ZIMP_IMPTO]
      ,CAST([DESC_QS] AS DECIMAL(6,2))/100 [DESC_QS]
      ,CASE WHEN len([ZVALNETO])=12 THEN CAST(SUBSTRING([ZVALNETO],2,11) AS DECIMAL(12,2))/-100 ELSE CAST([ZVALNETO] AS DECIMAL(12,2))/100 END [ZVALNETO]
      ,[CLS_PED]
      ,[IND_BONIF]
	  ,CASE WHEN len([ZVALNET_CFLETE])=12 THEN CAST(SUBSTRING([ZVALNET_CFLETE],2,11) AS DECIMAL(12,2))/-100 ELSE CAST([ZVALNET_CFLETE] AS DECIMAL(12,2))/100 END [ZVALNET_CFLETE]
	  ,CASE WHEN len([VAL_DESC_RR])=12 THEN CAST(SUBSTRING([VAL_DESC_RR],2,11) AS DECIMAL(12,2))/-100 ELSE CAST([VAL_DESC_RR] AS DECIMAL(12,2))/100 END [VAL_DESC_RR]
      ,CASE WHEN len([VAL_DESC_NR])=12 THEN CAST(SUBSTRING([VAL_DESC_NR],2,11) AS DECIMAL(12,2))/-100 ELSE CAST([VAL_DESC_NR] AS DECIMAL(12,2))/100 END [VAL_DESC_NR]
	  ,CASE WHEN len([VAL_DESC_QS])=12 THEN CAST(SUBSTRING([VAL_DESC_QS],2,11) AS DECIMAL(12,2))/-100 ELSE CAST([VAL_DESC_QS] AS DECIMAL(12,2))/100 END [VAL_DESC_QS]
	  ,CASE WHEN len([VAL_FLETE_APROV])=12 THEN CAST(SUBSTRING([VAL_FLETE_APROV],2,11) AS DECIMAL(12,2))/-100 ELSE CAST([VAL_FLETE_APROV] AS DECIMAL(12,2))/100 END [VAL_FLETE_APROV]
      ,CASE WHEN len([ZVALNETO_SF_QS])=12 THEN CAST(SUBSTRING([ZVALNETO_SF_QS],2,11) AS DECIMAL(12,2))/-100 ELSE CAST([ZVALNETO_SF_QS] AS DECIMAL(12,2))/100 END [ZVALNETO_SF_QS]
      ,CAST([TIPO_CAMBIO] AS DECIMAL(12,5))/100000 [TIPO_CAMBIO]
      ,CAST([PJE_DSCTO_CE] AS DECIMAL(5,2))/100 [PJE_DSCTO_CE]
	  ,CASE WHEN len([VALOR_DSCTO_CE])=12 THEN CAST(SUBSTRING([VALOR_DSCTO_CE],2,11) AS DECIMAL(12,2))/-100 ELSE CAST([VALOR_DSCTO_CE] AS DECIMAL(12,2))/100 END [VALOR_DSCTO_CE]
      ,CASE WHEN len([COSTO_UNIT])=12 THEN CAST(SUBSTRING([COSTO_UNIT],2,11) AS DECIMAL(12,2))/-100 ELSE CAST([COSTO_UNIT] AS DECIMAL(12,2))/100 END [COSTO_UNIT]
      ,[ORG_VTAS]
      ,[SECTOR]
      ,[CARACT_NEG]
      ,[TRAT_COMERCIAL]
      ,ARCHIVO
INTO mkt.SELLOUT_QZ_HISTW
  FROM mkt.SELLOUT_QZ_HIST_2014
WHERE archivo in (
'2014_05_QZ_SellOut(Ene).TXT',
'2014_09_QZ_SellOut(Feb).TXT',
'2014_14_QZ_SellOut(Marzo).TXT',
'2014_18_QZ_SellOut(Abril).TXT',
'2014_22_QZ_SellOut.TXT',
'2014_27_QZ_SellOut(Cierre Junio).TXT',
'2014_31_QZ_SellOut(Cierre Julio).txt',
'2014_35_QZ_SellOut.TXT',
'2014_40_QZ_SellOut(Cierre Setiembre).TXT',
'2014_44_QZ_SellOut(Cierre Octubre).TXT',
'2014_48_QZ_SellOut.txt'
);

INSERT INTO mkt.SELLOUT_QZ_HISTW
SELECT [ID]
      ,[FECHAGEN]
      ,[VBRP_MATKL]
      ,[VBRP_MATNR]
      ,[WPROD]
      ,[VBRK_KUNAG]
      ,[KNA1_STCD1]
      ,[UBIGEO]
      ,[COD_VEND]
      ,[COD_PROM]
      ,[FREE1]
      ,[COD_OFI]
      ,[COD_CENTRO]
      ,[COD_ALM]
      ,[VBAK_VBELN]
      ,[VBKD_BSARK_E]
      ,[VBRK_VBELN]
      ,[VBRP_POSNR]
      ,[VBRK_XBLNR]
      ,[VBRK_ERDAT]
      ,[VBRK_FKART]
      ,[VBRK_FKDAT]
      ,[VBRK_ZZRFOFI]
      ,[VBRP_CHARG]
      ,[VBRK_ZTERM]
      ,[VBRP_AUGRU_AUFT]
      ,[VBRK_FKSTO]
	  ,CASE WHEN len([VBRP_FKIMG])=12 THEN CAST(SUBSTRING([VBRP_FKIMG],2,11) AS DECIMAL(12,3))/-1000 ELSE CAST([VBRP_FKIMG] AS DECIMAL(12,3))/1000 END [VBRP_FKIMG]
      ,[VBRP_VRKME]
	  ,CAST([VBRP_ZZ_ZP01] AS DECIMAL(12,2))/100 [VBRP_ZZ_ZP01]
      ,[VBRK_WAERK]
      ,CAST([DESC_RR] AS DECIMAL(7,2))/100 [DESC_RR]
	  ,CAST([DESC_NR] AS DECIMAL(7,2))/100 [DESC_NR]
      ,CASE WHEN len([VBRP_KZWI1])=12 THEN CAST(SUBSTRING([VBRP_KZWI1],2,11) AS DECIMAL(12,2))/-100 ELSE CAST([VBRP_KZWI1] AS DECIMAL(12,2))/100 END [VBRP_KZWI1]
	  ,CASE WHEN len([ZVALVTA_UNI])=12 THEN CAST(SUBSTRING([ZVALVTA_UNI],2,11) AS DECIMAL(12,2))/-100 ELSE CAST([ZVALVTA_UNI] AS DECIMAL(12,2))/100 END [ZVALVTA_UNI]
	  ,CASE WHEN len([ZIMP_BRUTO])=12 THEN CAST(SUBSTRING([ZIMP_BRUTO],2,11) AS DECIMAL(12,2))/-100 ELSE CAST([ZIMP_BRUTO] AS DECIMAL(12,2))/100 END [ZIMP_BRUTO]
      ,CAST([ZMARGEN] AS DECIMAL(6,2))/100 [ZMARGEN]
	  ,CASE WHEN len([ZVAL_VTAIMP])=12 THEN CAST(SUBSTRING([ZVAL_VTAIMP],2,11) AS DECIMAL(12,2))/-100 ELSE CAST([ZVAL_VTAIMP] AS DECIMAL(12,2))/100 END [ZVAL_VTAIMP]
      ,CASE WHEN len([ZIMP_IMPTO])=12 THEN CAST(SUBSTRING([ZIMP_IMPTO],2,11) AS DECIMAL(12,2))/-100 ELSE CAST([ZIMP_IMPTO] AS DECIMAL(12,2))/100 END [ZIMP_IMPTO]
      ,CAST([DESC_QS] AS DECIMAL(6,2))/100 [DESC_QS]
      ,CASE WHEN len([ZVALNETO])=12 THEN CAST(SUBSTRING([ZVALNETO],2,11) AS DECIMAL(12,2))/-100 ELSE CAST([ZVALNETO] AS DECIMAL(12,2))/100 END [ZVALNETO]
      ,[CLS_PED]
      ,[IND_BONIF]
	  ,CASE WHEN len([ZVALNET_CFLETE])=12 THEN CAST(SUBSTRING([ZVALNET_CFLETE],2,11) AS DECIMAL(12,2))/-100 ELSE CAST([ZVALNET_CFLETE] AS DECIMAL(12,2))/100 END [ZVALNET_CFLETE]
	  ,CASE WHEN len([VAL_DESC_RR])=12 THEN CAST(SUBSTRING([VAL_DESC_RR],2,11) AS DECIMAL(12,2))/-100 ELSE CAST([VAL_DESC_RR] AS DECIMAL(12,2))/100 END [VAL_DESC_RR]
      ,CASE WHEN len([VAL_DESC_NR])=12 THEN CAST(SUBSTRING([VAL_DESC_NR],2,11) AS DECIMAL(12,2))/-100 ELSE CAST([VAL_DESC_NR] AS DECIMAL(12,2))/100 END [VAL_DESC_NR]
	  ,CASE WHEN len([VAL_DESC_QS])=12 THEN CAST(SUBSTRING([VAL_DESC_QS],2,11) AS DECIMAL(12,2))/-100 ELSE CAST([VAL_DESC_QS] AS DECIMAL(12,2))/100 END [VAL_DESC_QS]
	  ,CASE WHEN len([VAL_FLETE_APROV])=12 THEN CAST(SUBSTRING([VAL_FLETE_APROV],2,11) AS DECIMAL(12,2))/-100 ELSE CAST([VAL_FLETE_APROV] AS DECIMAL(12,2))/100 END [VAL_FLETE_APROV]
      ,CASE WHEN len([ZVALNETO_SF_QS])=12 THEN CAST(SUBSTRING([ZVALNETO_SF_QS],2,11) AS DECIMAL(12,2))/-100 ELSE CAST([ZVALNETO_SF_QS] AS DECIMAL(12,2))/100 END [ZVALNETO_SF_QS]
      ,CAST([TIPO_CAMBIO] AS DECIMAL(12,5))/100000 [TIPO_CAMBIO]
      ,CAST([PJE_DSCTO_CE] AS DECIMAL(5,2))/100 [PJE_DSCTO_CE]
	  ,CASE WHEN len([VALOR_DSCTO_CE])=12 THEN CAST(SUBSTRING([VALOR_DSCTO_CE],2,11) AS DECIMAL(12,2))/-100 ELSE CAST([VALOR_DSCTO_CE] AS DECIMAL(12,2))/100 END [VALOR_DSCTO_CE]
      ,CASE WHEN len([COSTO_UNIT])=12 THEN CAST(SUBSTRING([COSTO_UNIT],2,11) AS DECIMAL(12,2))/-100 ELSE CAST([COSTO_UNIT] AS DECIMAL(12,2))/100 END [COSTO_UNIT]
      ,[ORG_VTAS]
      ,[SECTOR]
      ,[CARACT_NEG]
      ,[TRAT_COMERCIAL]
      ,ARCHIVO
  FROM mkt.SELLOUT_QZ_HIST_2013;


INSERT INTO mkt.SELLOUT_QZ_HISTW
SELECT [ID]
      ,[FECHAGEN]
      ,[VBRP_MATKL]
      ,[VBRP_MATNR]
      ,[WPROD]
      ,[VBRK_KUNAG]
      ,[KNA1_STCD1]
      ,[UBIGEO]
      ,[COD_VEND]
      ,[COD_PROM]
      ,[FREE1]
      ,[COD_OFI]
      ,[COD_CENTRO]
      ,[COD_ALM]
      ,[VBAK_VBELN]
      ,[VBKD_BSARK_E]
      ,[VBRK_VBELN]
      ,[VBRP_POSNR]
      ,[VBRK_XBLNR]
      ,[VBRK_ERDAT]
      ,[VBRK_FKART]
      ,[VBRK_FKDAT]
      ,[VBRK_ZZRFOFI]
      ,[VBRP_CHARG]
      ,[VBRK_ZTERM]
      ,[VBRP_AUGRU_AUFT]
      ,[VBRK_FKSTO]
	  ,CASE WHEN len([VBRP_FKIMG])=12 THEN CAST(SUBSTRING([VBRP_FKIMG],2,11) AS DECIMAL(12,3))/-1000 ELSE CAST([VBRP_FKIMG] AS DECIMAL(12,3))/1000 END [VBRP_FKIMG]
      ,[VBRP_VRKME]
	  ,CAST([VBRP_ZZ_ZP01] AS DECIMAL(12,2))/100 [VBRP_ZZ_ZP01]
      ,[VBRK_WAERK]
      ,CAST([DESC_RR] AS DECIMAL(7,2))/100 [DESC_RR]
	  ,CAST([DESC_NR] AS DECIMAL(7,2))/100 [DESC_NR]
      ,CASE WHEN len([VBRP_KZWI1])=12 THEN CAST(SUBSTRING([VBRP_KZWI1],2,11) AS DECIMAL(12,2))/-100 ELSE CAST([VBRP_KZWI1] AS DECIMAL(12,2))/100 END [VBRP_KZWI1]
	  ,CASE WHEN len([ZVALVTA_UNI])=12 THEN CAST(SUBSTRING([ZVALVTA_UNI],2,11) AS DECIMAL(12,2))/-100 ELSE CAST([ZVALVTA_UNI] AS DECIMAL(12,2))/100 END [ZVALVTA_UNI]
	  ,CASE WHEN len([ZIMP_BRUTO])=12 THEN CAST(SUBSTRING([ZIMP_BRUTO],2,11) AS DECIMAL(12,2))/-100 ELSE CAST([ZIMP_BRUTO] AS DECIMAL(12,2))/100 END [ZIMP_BRUTO]
      ,CAST([ZMARGEN] AS DECIMAL(6,2))/100 [ZMARGEN]
	  ,CASE WHEN len([ZVAL_VTAIMP])=12 THEN CAST(SUBSTRING([ZVAL_VTAIMP],2,11) AS DECIMAL(12,2))/-100 ELSE CAST([ZVAL_VTAIMP] AS DECIMAL(12,2))/100 END [ZVAL_VTAIMP]
      ,CASE WHEN len([ZIMP_IMPTO])=12 THEN CAST(SUBSTRING([ZIMP_IMPTO],2,11) AS DECIMAL(12,2))/-100 ELSE CAST([ZIMP_IMPTO] AS DECIMAL(12,2))/100 END [ZIMP_IMPTO]
      ,CAST([DESC_QS] AS DECIMAL(6,2))/100 [DESC_QS]
      ,CASE WHEN len([ZVALNETO])=12 THEN CAST(SUBSTRING([ZVALNETO],2,11) AS DECIMAL(12,2))/-100 ELSE CAST([ZVALNETO] AS DECIMAL(12,2))/100 END [ZVALNETO]
      ,[CLS_PED]
      ,[IND_BONIF]
	  ,CASE WHEN len([ZVALNET_CFLETE])=12 THEN CAST(SUBSTRING([ZVALNET_CFLETE],2,11) AS DECIMAL(12,2))/-100 ELSE CAST([ZVALNET_CFLETE] AS DECIMAL(12,2))/100 END [ZVALNET_CFLETE]
	  ,CASE WHEN len([VAL_DESC_RR])=12 THEN CAST(SUBSTRING([VAL_DESC_RR],2,11) AS DECIMAL(12,2))/-100 ELSE CAST([VAL_DESC_RR] AS DECIMAL(12,2))/100 END [VAL_DESC_RR]
      ,CASE WHEN len([VAL_DESC_NR])=12 THEN CAST(SUBSTRING([VAL_DESC_NR],2,11) AS DECIMAL(12,2))/-100 ELSE CAST([VAL_DESC_NR] AS DECIMAL(12,2))/100 END [VAL_DESC_NR]
	  ,CASE WHEN len([VAL_DESC_QS])=12 THEN CAST(SUBSTRING([VAL_DESC_QS],2,11) AS DECIMAL(12,2))/-100 ELSE CAST([VAL_DESC_QS] AS DECIMAL(12,2))/100 END [VAL_DESC_QS]
	  ,CASE WHEN len([VAL_FLETE_APROV])=12 THEN CAST(SUBSTRING([VAL_FLETE_APROV],2,11) AS DECIMAL(12,2))/-100 ELSE CAST([VAL_FLETE_APROV] AS DECIMAL(12,2))/100 END [VAL_FLETE_APROV]
      ,CASE WHEN len([ZVALNETO_SF_QS])=12 THEN CAST(SUBSTRING([ZVALNETO_SF_QS],2,11) AS DECIMAL(12,2))/-100 ELSE CAST([ZVALNETO_SF_QS] AS DECIMAL(12,2))/100 END [ZVALNETO_SF_QS]
      ,CAST([TIPO_CAMBIO] AS DECIMAL(12,5))/100000 [TIPO_CAMBIO]
      ,CAST([PJE_DSCTO_CE] AS DECIMAL(5,2))/100 [PJE_DSCTO_CE]
	  ,CASE WHEN len([VALOR_DSCTO_CE])=12 THEN CAST(SUBSTRING([VALOR_DSCTO_CE],2,11) AS DECIMAL(12,2))/-100 ELSE CAST([VALOR_DSCTO_CE] AS DECIMAL(12,2))/100 END [VALOR_DSCTO_CE]
      ,CASE WHEN len([COSTO_UNIT])=12 THEN CAST(SUBSTRING([COSTO_UNIT],2,11) AS DECIMAL(12,2))/-100 ELSE CAST([COSTO_UNIT] AS DECIMAL(12,2))/100 END [COSTO_UNIT]
      ,[ORG_VTAS]
      ,[SECTOR]
      ,[CARACT_NEG]
      ,[TRAT_COMERCIAL]
      ,ARCHIVO
  FROM mkt.SELLOUT_QZ_HIST_2015
WHERE archivo in (
'2015_01_QZ_SellOut.TXT',
'2015_05_QZ_SellOut.TXT',
'2015_09_QZ_SellOut.TXT',
'2015_14_QZ_SellOut(Cierre Marzo).TXT',
'2015_18_QZ_SellOut(Cierre Abril).TXT',
'2015_22_QZ_SellOut.TXT',
'2015_27_QZ_SellOut(Cierre Junio).TXT'
)
;


SELECT DISTINCT archivo FROM mkt.SELLOUT_QZ_HIST_2014
WHERE archivo in (
'2014_05_QZ_SellOut(Ene).TXT',
'2014_09_QZ_SellOut(Feb).TXT',
'2014_14_QZ_SellOut(Marzo).TXT',
'2014_18_QZ_SellOut(Abril).TXT',
'2014_22_QZ_SellOut.TXT',
'2014_27_QZ_SellOut(Cierre Junio).TXT',
'2014_31_QZ_SellOut(Cierre Julio).txt',
'2014_35_QZ_SellOut.TXT',
'2014_40_QZ_SellOut(Cierre Setiembre).TXT',
'2014_44_QZ_SellOut(Cierre Octubre).TXT',
'2014_48_QZ_SellOut.txt'
)
