SELECT substring(VBRK_FKDAT,1,6) PERIODO,
  sum(ZVALVTA_UNI) ZVALVTA_UNI,
sum(ZIMP_BRUTO) ZIMP_BRUTO,
sum(ZMARGEN) ZMARGEN,
sum(ZVAL_VTAIMP) ZVAL_VTAIMP,
sum(ZIMP_IMPTO) ZIMP_IMPTO,
sum(DESC_QS) DESC_QS,
  sum(ZVALNETO_SF_QS) ZVALNETO_SF_QS,
  SUM(ZVALNETO) ZVALNETO,
  SUM(ZVALNET_CFLETE) ZVALNET_CFLETE,
  SUM(VAL_DESC_NR) VAL_DESC_NR,
  SUM(VAL_DESC_QS) VAL_DESC_QS,
  SUM(VAL_DESC_RR) VAL_DESC_RR
FROM mkt.SELLOUT_QZ_HISTW
GROUP BY substring(VBRK_FKDAT,1,6)
ORDER BY 1;





SELECT
  VBRK_KUNAG,
  KNA1_STCD1
FROM (
  SELECT
    VBRK_KUNAG,
    KNA1_STCD1,
    COUNT(1) OVER (PARTITION BY VBRK_KUNAG) CONT
  FROM mkt.SELLOUT_QZ_HISTW
  GROUP BY VBRK_KUNAG,KNA1_STCD1
) A
WHERE CONT>1
ORDER BY 1


SELECT FECHAGEN,VBRK_KUNAG,KNA1_STCD1,ARCHIVO FROM mkt.SELLOUT_QZ_HISTW
WHERE VBRK_KUNAG='0000406224'
ORDER BY 1

SELECT FECHAGEN,VBRK_KUNAG,KNA1_STCD1,ARCHIVO FROM mkt.SELLOUT_QZ_HISTW
WHERE VBRK_KUNAG='0000418029'
ORDER BY 1

SELECT * FROM per.MAESTRO_TIEMPO
WHERE Año_GL='2015' and Semana_GL='22'


SELECT * FROM mkt.SELLOUT_QZ_HISTW